

-- Flown / Flight Operation / EDMS Sabre
CREATE OR REPLACE PROCEDURE PRAXIS.SQP05425 ( IN IN_CCUST VARCHAR(3),
                                   IN IN_FPROCF VARCHAR(8),
                                   IN IN_FPROCT VARCHAR(8),
                                   IN IN_STVAL VARCHAR(1),
                                   IN IN_TPAX VARCHAR(1),
                                   IN IN_FTE VARCHAR(3),
                                   IN IN_TICKET VARCHAR(13),
                                   IN IN_STNOTUSED VARCHAR(13),
                                   INOUT IO_PAGNUM INTEGER,
                                   INOUT IO_PAGROW INTEGER,
                                   INOUT IO_TOTPAG INTEGER,
                                   INOUT IO_TOTROW INTEGER )
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC PRAXIS.SQP05425

BEGIN
	
	/*
	 * Detalle de EMD
	 */
	
	DECLARE V_SQL VARCHAR ( 8000 ) ;
	DECLARE V_WHERE VARCHAR ( 5000 ) DEFAULT '' ;
	
	--paginado
	DECLARE PAGROWINIT INTEGER ;
	DECLARE SQLCNT01 VARCHAR ( 5000 ) ;
	DECLARE SQLPAG01 VARCHAR ( 5000 ) ;
	DECLARE CURQRY01 CURSOR FOR STMTQRY01 ;
	DECLARE CURCNT01 CURSOR FOR STMTCNT01 ;
			
	SET V_SQL = '
		SELECT ROW_NUMBER() OVER (ORDER BY A.CCIA,A.FORMA,A.SERIE) as RN,
		A.CCUST,A.CCIA,A.FORMA,A.SERIE,A.CUPON,A.SEQVTA,A.SEQ,A.STVAL,A.FTE,A.GRUPO,A.FPROC,A.CDOC,A.TDOC,A.PSVVTA,A.AGTIA,A.FVTA,TRIM(A.TPAX) AS TPAX,
		A.CARR,A.CARROP,A.VCPN,A.COMISI,A.SCOMISI,A.YQ,A.MDACP,A.VCPNRV,A.COMREV,A.SCOMREV,A.YQREV,A.RFIS,A.RFIC,A.TUSO,A.DFLIGHT,A.NFLIGHT,
		A.CDEPART,A.CARRIVA,A.LOTE,A.STCHG,A.STUSE,A.USCR,A.FECR,A.HOCR,A.USUP,A.FEUP,A.HOUP 
		FROM PRAXIS.A4622 A WHERE CCUST = ''{CCUST}'' 
		{WHERE}
	' ;
	
	--SETEO DE VARIABLES
	SET V_SQL = REPLACE ( V_SQL , '{CCUST}' , IN_CCUST ) ;
	
	IF IN_FPROCT <> '' THEN
		SET V_WHERE = V_WHERE || ' AND FPROC BETWEEN ''' || IN_FPROCF || ''' AND ''' || IN_FPROCT || '''' ;
	ELSE
		SET V_WHERE = V_WHERE || ' AND FPROC = ''' || IN_FPROCF || '''' ;
	END IF ;
	
	IF IN_STVAL <> '' THEN
		IF IN_STVAL = 'X' THEN
			SET V_WHERE = V_WHERE || ' AND STVAL <> ''1''' ;
		ELSE
			SET V_WHERE = V_WHERE || ' AND STVAL = ''' || IN_STVAL || '''' ;
		END IF ;
	END IF ;
	
	IF IN_FTE <> '' THEN
		SET V_WHERE = V_WHERE || ' AND FTE = ''' || IN_FTE || '''' ;
	END IF ;
	
	IF IN_TPAX <> '' THEN
		SET V_WHERE = V_WHERE || ' AND TPAX = ''' || IN_TPAX || '''' ;
	END IF ;
	
	IF IN_TICKET <> '' THEN
		IF LENGTH ( TRIM ( IN_TICKET ) ) = 13 THEN
			SET V_WHERE = V_WHERE || ' AND CCIA = ''' || LEFT ( IN_TICKET , 3 ) || '''' ;
			SET V_WHERE = V_WHERE || ' AND FORMA = ''' || SUBSTR ( IN_TICKET , 4 , 4 ) || '''' ;
			SET V_WHERE = V_WHERE || ' AND SERIE = ''' || SUBSTR ( IN_TICKET , 8 , 6 ) || '''' ;
		END IF ;
	END IF ;
	
	IF IN_STNOTUSED = 'NOTUSED' THEN
    	SET V_WHERE = V_WHERE || ' AND NVL(STUSE, '''') NOT IN (''USED'', ''OK'')' ;
	ELSEIF IN_STNOTUSED <> '' THEN
	    SET V_WHERE = V_WHERE || ' AND STUSE = ''' || IN_STNOTUSED || '''' ;
	END IF;
	
	SET V_SQL = REPLACE ( V_SQL , '{WHERE}' , V_WHERE ) ;
	
	/*
	 * Paginado
	 */
	
	IF IO_TOTROW = - 1 THEN
		SET SQLCNT01 = ' SELECT COUNT (*) AS F_TOTROW FROM ( ' || V_SQL ;
	
		SET SQLCNT01 = SQLCNT01 CONCAT ' ) AS TBCOUNT' ;
		
		PREPARE STMTCNT01 FROM SQLCNT01 ;
		OPEN CURCNT01 ;
		FETCH_LOOP :
			LOOP
			FETCH CURCNT01 INTO IO_TOTROW ;
			LEAVE FETCH_LOOP ;
			END LOOP FETCH_LOOP ;
			CLOSE CURCNT01 ;
	END IF ;
	
	SET IO_PAGNUM = PRAXIS . F0001 ( 'PAGNUM' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_PAGROW = PRAXIS . F0001 ( 'PAGROW' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_TOTPAG = PRAXIS . F0001 ( 'TOTPAG' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_TOTROW = PRAXIS . F0001 ( 'TOTROW' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET PAGROWINIT = PRAXIS . F0001 ( 'PRINIT' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	
	SET SQLPAG01 = 'SELECT * FROM ( ' CONCAT V_SQL CONCAT ' ) AS       
	RS WHERE RS.RN >  ' CONCAT PAGROWINIT ;
	IF IO_PAGROW > 0 THEN
		SET SQLPAG01 = SQLPAG01 CONCAT ' FETCH FIRST ' CONCAT IO_PAGROW CONCAT ' ROWS ONLY' ;
	END IF ;
	
	
	PREPARE STMTQRY01 FROM SQLPAG01 ;
	OPEN CURQRY01 ;
END

