SELECT * FROM PRAXIS.A1838



-- revisar longitud de campos de la tabla
SELECT COLUMN_NAME, LENGTH
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'PRAXIS'
AND TABLE_NAME = 'A1838'
AND COLUMN_NAME IN ('A1838CENCO','A1838CUENT');



-- CAMBIAR LONGITUD DE CAMPOS DE TABLA
ALTER TABLE PRAXIS.A1838
ALTER COLUMN A1838CENCO SET DATA TYPE VARCHAR(7);


ALTER TABLE PRAXIS.A1838
ALTER COLUMN A1838CUENT SET DATA TYPE VARCHAR(6);