



SELECT * FROM PXFARES.A2532
--------------------------------------------------------------------



CREATE OR REPLACE PROCEDURE PXFARES.SQP05832  
(
   IN IN_OPTION VARCHAR(1),     -- 1 = A2439DATE, 2 = A2439FCARG
   IN IN_DATE   VARCHAR(8),     -- Fecha a filtrar
   INOUT IO_PAGNUM INTEGER,
   INOUT IO_PAGROW INTEGER,
   INOUT IO_TOTPAG INTEGER,
   INOUT IO_TOTROW INTEGER
)
RESULT SETS 1
LANGUAGE SQL
SPECIFIC PXFARES.SQP05832
BEGIN
    DECLARE V_SQL        VARCHAR(30000);  
    DECLARE PAGROWINIT   INTEGER;
    DECLARE SQLPAG01     VARCHAR(30000);
    DECLARE CURQRY01 CURSOR WITH RETURN FOR STMTQRY01;


    SET V_SQL = '
        SELECT ROW_NUMBER() OVER (ORDER BY X.A2532IDFIL DESC) AS RN,
               X.*
        FROM PXFARES.A2439 X
        WHERE 1=1
    ';

    
    IF IN_DATE IS NOT NULL AND IN_DATE <> '' THEN
        IF IN_OPTION = '1' THEN
            -- Filtrar por A2439DATE
            SET V_SQL = V_SQL || ' AND X.A2439DATE = ''' || IN_DATE || '''';
        ELSEIF IN_OPTION = '2' THEN
            -- Filtrar por A2439FCARG
            SET V_SQL = V_SQL || ' AND X.A2439FCARG = ''' || IN_DATE || '''';
        END IF;
    END IF;

    --------------------------------------------------------------------
    -- Paginación
    --------------------------------------------------------------------
    SET IO_PAGNUM  = PRAXIS.F0001('PAGNUM', IO_PAGNUM, IO_PAGROW, IO_TOTPAG, IO_TOTROW);
    SET IO_PAGROW  = PRAXIS.F0001('PAGROW', IO_PAGNUM, IO_PAGROW, IO_TOTPAG, IO_TOTROW);
    SET IO_TOTPAG  = PRAXIS.F0001('TOTPAG', IO_PAGNUM, IO_PAGROW, IO_TOTPAG, IO_TOTROW);
    SET IO_TOTROW  = PRAXIS.F0001('TOTROW', IO_PAGNUM, IO_PAGROW, IO_TOTPAG, IO_TOTROW);
    SET PAGROWINIT = PRAXIS.F0001('PRINIT', IO_PAGNUM, IO_PAGROW, IO_TOTPAG, IO_TOTROW);

    IF IO_TOTROW = -1 THEN
        SET SQLPAG01 = 'SELECT COUNT(1) FROM (' || V_SQL || ') AS C';
        PREPARE STMTQRY01 FROM SQLPAG01;
        OPEN CURQRY01;
        FETCH CURQRY01 INTO IO_TOTROW;
        CLOSE CURQRY01;
    END IF;

    SET SQLPAG01 = 'SELECT * FROM (' || V_SQL || ') AS RS WHERE RS.RN > ' 
                    || CAST(PAGROWINIT AS VARCHAR(20));

    IF IO_PAGROW > 0 THEN
        SET SQLPAG01 = SQLPAG01 || ' FETCH FIRST ' || CAST(IO_PAGROW AS VARCHAR(20)) || ' ROWS ONLY';
    END IF;

    
    PREPARE STMTQRY01 FROM SQLPAG01;
    OPEN CURQRY01;

END

