


-- PRAXIS.SQP05015
-- Búsqueda Load Contorl Report

-----------------------------------------------------------------------------------------------


CREATE OR REPLACE PROCEDURE PRAXIS.SQP05015 ( IN VP_CCUST CHAR(3),
                                   IN VP_FPROC1 CHAR(8),
                                   IN VP_FUEN VARCHAR(3),
                                   IN VP_PAIS VARCHAR(2) )
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC PRAXIS.SQP05015

BEGIN
	/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
    ++ HISTORIAL DE CAMBIOS
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++  DEV     CODE    DATE        DESCRIPCION                                        
    ++  VHO     202300  14/07/2023  Creacion de SP
    ++  YR      1026    21/10/2025  Condición ARC y comentarios
	++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
	DECLARE VL_QRYSQL , VL_QRYSQL_1 VARCHAR ( 4000 ) ;
	DECLARE VL_EOF , VL_EOF_1 , VL_NHOT , VL_DIADELASEMANA INTEGER DEFAULT 0 ;
	DECLARE VL_A4469PDATE CHAR ( 8 ) ;
	DECLARE VL_A4469PDATE_1 VARCHAR ( 15 ) ;
	DECLARE VL_FOUND , VL_FLAG CHAR ( 1 ) ;
	DECLARE VL_LABEL1 , VL_LABEL2 , VL_LABEL3 , VL_LABEL4 , VL_LABEL5 , VL_LABEL6 , VL_LABEL7 CHAR ( 1 ) ;
	DECLARE VL_COUNTRY VARCHAR ( 40 ) ;
	DECLARE VL_A4469STATU , VL_A4469IDATE VARCHAR ( 60 ) ;
	DECLARE VL_A4469TSALE , VL_A4469TEXCH , VL_A4469TRFND , VL_A4469TMEMO , VL_A4469TVOID INT ;
	DECLARE VL_PDATE VARCHAR ( 12 ) ;
	DECLARE VL_COUNT INT ;
	DECLARE VL_A4859COME VARCHAR ( 300 ) DEFAULT '' ; --new
	
	DECLARE VL_SQLQRY VARCHAR ( 2000 ) DEFAULT '' ;	
	DECLARE CURQRY CURSOR FOR STMTQRY ;
	
	-- SELECT * FROM SESSION.temp99 
	DECLARE GLOBAL TEMPORARY TABLE SESSION . TEMP99 (
		NHOT INT ,
		COUNTRY VARCHAR ( 60 ) ,
		COUNTRY_CODE VARCHAR ( 3 ) ,
		CURR CHAR ( 3 ) ,		
		--		
		PRDA1 CHAR ( 8 ) , PRDA1_ VARCHAR ( 15 ) , STATUS1 VARCHAR ( 10 ) , ISSUDT1 VARCHAR ( 150 ) ,		
		SALE1 INT , EXCH1 INT , RFND1 INT , MEMO1 INT , VOID1 INT , LABEL1 CHAR ( 1 ) , FLG1 CHAR ( 1 ) DEFAULT '' , COMMENT1 VARCHAR ( 300 ) ,
		--
		PRDA2 CHAR ( 8 ) , PRDA2_ VARCHAR ( 15 ) , STATUS2 VARCHAR ( 10 ) , ISSUDT2 VARCHAR ( 150 ) ,
		SALE2 INT , EXCH2 INT , RFND2 INT , MEMO2 INT , VOID2 INT , LABEL2 CHAR ( 1 ) , FLG2 CHAR ( 1 ) DEFAULT '' , COMMENT2 VARCHAR ( 300 ) ,
		--
		PRDA3 CHAR ( 8 ) , PRDA3_ VARCHAR ( 15 ) , STATUS3 VARCHAR ( 10 ) , ISSUDT3 VARCHAR ( 150 ) ,		
		SALE3 INT , EXCH3 INT , RFND3 INT , MEMO3 INT , VOID3 INT , LABEL3 CHAR ( 1 ) , FLG3 CHAR ( 1 ) DEFAULT '' , COMMENT3 VARCHAR ( 300 ) ,
		--
		PRDA4 CHAR ( 8 ) , PRDA4_ VARCHAR ( 15 ) , STATUS4 VARCHAR ( 10 ) , ISSUDT4 VARCHAR ( 150 ) ,		
		SALE4 INT , EXCH4 INT , RFND4 INT , MEMO4 INT , VOID4 INT , LABEL4 CHAR ( 1 ) , FLG4 CHAR ( 1 ) DEFAULT '' , COMMENT4 VARCHAR ( 300 ) ,
		--
		PRDA5 CHAR ( 8 ) , PRDA5_ VARCHAR ( 15 ) , STATUS5 VARCHAR ( 10 ) , ISSUDT5 VARCHAR ( 150 ) ,		
		SALE5 INT , EXCH5 INT , RFND5 INT , MEMO5 INT , VOID5 INT , LABEL5 CHAR ( 1 ) , FLG5 CHAR ( 1 ) DEFAULT '' , COMMENT5 VARCHAR ( 300 ) ,
		--
		PRDA6 CHAR ( 8 ) , PRDA6_ VARCHAR ( 15 ) , STATUS6 VARCHAR ( 10 ) , ISSUDT6 VARCHAR ( 150 ) ,		
		SALE6 INT , EXCH6 INT , RFND6 INT , MEMO6 INT , VOID6 INT , LABEL6 CHAR ( 1 ) , FLG6 CHAR ( 1 ) DEFAULT '' , COMMENT6 VARCHAR ( 300 ) ,
		--
		PRDA7 CHAR ( 8 ) , PRDA7_ VARCHAR ( 15 ) , STATUS7 VARCHAR ( 10 ) , ISSUDT7 VARCHAR ( 150 ) ,	
		SALE7 INT , EXCH7 INT , RFND7 INT , MEMO7 INT , VOID7 INT , LABEL7 CHAR ( 1 ) , FLG7 CHAR ( 1 ) DEFAULT '' , COMMENT7 VARCHAR ( 300 )
	) WITH REPLACE ON COMMIT PRESERVE ROWS NOT LOGGED ;

	-- Genera 7 dias desde una "Fecha inicial". 
	SET VL_A4469PDATE = VP_FPROC1 ;
	SET VL_EOF = 0 ;
	SET VL_FOUND = 'N' ;
		
	
	WHILE ( VL_EOF < 7 ) DO
		SET VL_EOF = VL_EOF + 1 ;
		
		-- insert into praxis.qry_log1 values(VL_A4469PDATE);
		
		SET VL_EOF_1 = 0 ;
		RW0 : FOR RW0_ AS RW0__ CURSOR FOR
			SELECT * FROM PRAXIS . A4493
			WHERE	A4493CCUST = VP_CCUST AND
					A4493PRDA = VL_A4469PDATE AND
					A4493FUENT = ( CASE WHEN VP_FUEN = '' THEN A4493FUENT ELSE VP_FUEN END ) AND
					A4493PAIS = ( CASE WHEN VP_PAIS = '' THEN A4493PAIS ELSE VP_PAIS END )
		DO		
			/* OBTIENE COMENTARIO NUEVO*/
			
			SET VL_A4859COME = '' ;
			
			SELECT A4859COME
			INTO VL_A4859COME
			FROM PRAXIS . A4859
			WHERE A4859CCUST = RW0_ . A4493CCUST
			--AND A4859FUENT = RW0_.A4493FUENT
			AND A4859PAIS = RW0_ . A4493PAIS
			AND A4859MDA = RW0_ . A4493MDA
			AND A4859FECHA = RW0_ . A4493PRDA
			AND UPPER ( TRIM ( A4859DIAT ) ) = UPPER ( TRIM ( RW0_ . A4493PRDD ) )
			FETCH FIRST 1 ROW ONLY ;
			
			--INSERT INTO PRAXIS . QRY_LOG1 VALUES ( VL_A4859COME ) ;
			
			
			SET VL_EOF_1 = VL_EOF ;			
			-- insert into praxis.qry_log1 values(VL_A4469PDATE);
			-- insert into praxis.qry_log1 values(VL_EOF_1);
			
			
			
			SET VL_QRYSQL = 'INSERT INTO SESSION.TEMP99 ( NHOT, COUNTRY, COUNTRY_CODE, CURR, ' ;
			SET VL_QRYSQL = VL_QRYSQL || 'PRDA' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'PRDA' || VL_EOF || '_,' ;
			SET VL_QRYSQL = VL_QRYSQL || 'STATUS' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'ISSUDT' || VL_EOF || ',' ;			
			SET VL_QRYSQL = VL_QRYSQL || 'SALE' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'EXCH' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'RFND' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'MEMO' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'VOID' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'COMMENT' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'FLG' || VL_EOF || ',' ; -- new	
			SET VL_QRYSQL = VL_QRYSQL || 'LABEL' || VL_EOF ;		
			SET VL_QRYSQL = VL_QRYSQL || ' )' ;
			
			SET VL_QRYSQL = VL_QRYSQL || ' VALUES (''' ;
			SET VL_QRYSQL = VL_QRYSQL || A4493HOTN || ''',''' || TRIM ( A4493PAISD ) || ''',''' || A4493PAIS || ''',''' || A4493MDA || ''',''' ;
			SET VL_QRYSQL = VL_QRYSQL || A4493PRDA || ''',''' || A4493PRDD || ''',''' || TRIM ( A4493STAT ) || ''',''' || TRIM ( A4493ISSUD ) || ''',''' ;
			SET VL_QRYSQL = VL_QRYSQL || A4493SALE || ''',''' || A4493EXCH || ''',''' || A4493RFND || ''',''' || A4493MEMO || ''',''' || A4493VOID || ''',''' ;
			SET VL_QRYSQL = VL_QRYSQL || VL_A4859COME || ''',''' ;
			SET VL_QRYSQL = VL_QRYSQL || A4493FLAG || ''',''' ;
			
		
			-- SE AGREGO PARA PAIS 'VE'
			SET VL_DIADELASEMANA = DAYOFWEEK ( DATE ( SUBSTR ( VL_A4469PDATE , 1 , 4 ) || '-' || SUBSTR ( VL_A4469PDATE , 5 , 2 ) || '-' || SUBSTR ( VL_A4469PDATE , 7 , 2 ) ) ) ;

			--IF A4493PAIS = 'VE' AND ( VL_DIADELASEMANA = 1 OR VL_DIADELASEMANA = 7 ) THEN
			--IF A4493PAIS = 'VE' THEN
			--    SET A4493LABEL = 'A' ;
			--END IF ;
			
			-- ASR MARTES
			--IF TRIM ( A4493FUENT ) = 'ARC' AND VL_DIADELASEMANA = 3 THEN
			--SET A4493LABEL = 'A' ;
			--END IF ;
			
			
			SET VL_QRYSQL = VL_QRYSQL || A4493LABEL || ''')' ;
			
			--INSERT INTO PRAXIS . QRY_LOG1 VALUES ( VL_QRYSQL ) ;

			
			SET VL_FLAG = 'N' ;
			IF A4493FUENT = 'BSP' THEN		
				SELECT 'S' INTO VL_FLAG FROM SESSION . TEMP99 WHERE COUNTRY_CODE = A4493PAIS AND CURR = A4493MDA ;
			ELSE
				SELECT 'S' INTO VL_FLAG FROM SESSION . TEMP99 WHERE COUNTRY = A4493FUENT ; -- ASR/ARC
			END IF ;
			
			IF IFNULL ( VL_FLAG , 'N' ) = 'N' THEN				
				EXECUTE IMMEDIATE VL_QRYSQL ; -- INSERT
			ELSE
				SET VL_QRYSQL_1 = 'UPDATE SESSION.temp99 SET ' ;	
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' NHOT=''' || A4493HOTN || ''',' ;		
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' PRDA' || VL_EOF || '=''' || A4493PRDA || ''', ' ;									
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' PRDA' || VL_EOF || '_ =''' || A4493PRDD || ''', ' ;	
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' STATUS' || VL_EOF || '=''' || TRIM ( A4493STAT ) || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' ISSUDT' || VL_EOF || '=''' || TRIM ( A4493ISSUD ) || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' SALE' || VL_EOF || '=''' || A4493SALE || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' EXCH' || VL_EOF || '=''' || A4493EXCH || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' RFND' || VL_EOF || '=''' || A4493RFND || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' MEMO' || VL_EOF || '=''' || A4493MEMO || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' VOID' || VL_EOF || '=''' || A4493VOID || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' LABEL' || VL_EOF || '=''' || A4493LABEL || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' FLG' || VL_EOF || '=''' || A4493FLAG || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' COMMENT' || VL_EOF || '=''' || VL_A4859COME || ''' ' ;

												
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' WHERE COUNTRY_CODE=''' || A4493PAIS || ''' ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' AND CURR='''	|| A4493MDA	|| ''' ' ;													
				EXECUTE IMMEDIATE VL_QRYSQL_1 ;								
			END IF ;	
				
			
		END FOR RW0 ;
		
		-- ADD INTERVAL 1 DAY		
		SET VL_PDATE = DATE ( DATE ( SUBSTR ( VL_A4469PDATE , 1 , 4 ) || '-' || SUBSTR ( VL_A4469PDATE , 5 , 2 ) || '-' || SUBSTR ( VL_A4469PDATE , 7 , 2 ) ) ) + 1 DAYS ;	
		SET VL_A4469PDATE = YEAR ( VL_PDATE ) || LPAD ( MONTH ( VL_PDATE ) , 2 , '0' ) || LPAD ( DAY ( VL_PDATE ) , 2 , '0' ) ;
		
	END WHILE ;

		
	SET VL_SQLQRY = 'SELECT ROW_NUMBER() OVER( ORDER BY COUNTRY_CODE ) AS NHOT, COUNTRY, COUNTRY_CODE, CURR,
	 PRDA1, PRDA1_, STATUS1, ISSUDT1, SALE1, EXCH1, RFND1, MEMO1, VOID1, LABEL1, FLG1, COMMENT1,
	 PRDA2, PRDA2_, STATUS2, ISSUDT2, SALE2, EXCH2, RFND2, MEMO2, VOID2, LABEL2, FLG2, COMMENT2,
	 PRDA3, PRDA3_, STATUS3, ISSUDT3, SALE3, EXCH3, RFND3, MEMO3, VOID3, LABEL3, FLG3, COMMENT3,
	 PRDA4, PRDA4_, STATUS4, ISSUDT4, SALE4, EXCH4, RFND4, MEMO4, VOID4, LABEL4, FLG4, COMMENT4,
	 PRDA5, PRDA5_, STATUS5, ISSUDT5, SALE5, EXCH5, RFND5, MEMO5, VOID5, LABEL5, FLG5, COMMENT5,
	 PRDA6, PRDA6_, STATUS6, ISSUDT6, SALE6, EXCH6, RFND6, MEMO6, VOID6, LABEL6, FLG6, COMMENT6,
	 PRDA7, PRDA7_, STATUS7, ISSUDT7, SALE7, EXCH7, RFND7, MEMO7, VOID7, LABEL7, FLG7, COMMENT7
	 FROM SESSION.temp99 ' ;
	PREPARE STMTQRY FROM VL_SQLQRY ;
	OPEN CURQRY ;
		
	END
	
	
	
GRANT ALL ON PROCEDURE PRAXIS.SQP05015 TO PUBLIC  -- PARA TODOS PUEDAN USAR



SELECT DISTINCT A4493LABEL 
	FROM PRAXIS.A4493
	ORDER BY A4493LABEL;
