--<ScriptOptions statementTerminator=";"/>

SELECT * FROM SESSION.temp99
--- DECLARAR TABLA ANTES DE EJECUTAR EL SP

--/*
DECLARE GLOBAL TEMPORARY TABLE SESSION . TEMP99 (
		NHOT INT ,
		COUNTRY VARCHAR ( 60 ) ,
		COUNTRY_CODE VARCHAR ( 3 ) ,
		CURR CHAR ( 3 ) ,		
		--		
		PRDA1 CHAR ( 8 ) , PRDA1_ VARCHAR ( 15 ) , STATUS1 VARCHAR ( 10 ) , ISSUDT1 VARCHAR ( 150 ) ,		
		SALE1 INT , EXCH1 INT , RFND1 INT , MEMO1 INT , VOID1 INT , LABEL1 CHAR ( 1 ) , FLG1 CHAR ( 1 ) DEFAULT ''
	) WITH REPLACE ON COMMIT PRESERVE ROWS NOT LOGGED
--*/


--SELECT * FROM PRAXIS.A4469


	
CALL PRAXIS.SQP05069 ('139','20220305',PRAXIS.OUT_SQL_SQLCODE,PRAXIS.OUT_SQL_MESSAGE)

CREATE OR REPLACE VARIABLE PRAXIS.OUT_SQL_SQLCODE INTEGER
CREATE OR REPLACE VARIABLE PRAXIS.OUT_SQL_MESSAGE VARCHAR(300)
	
CALL 
CREATE OR REPLACE PROCEDURE PRAXIS.SQP05069 ( IN VP_CCUST CHAR(3),
                                   IN VP_FPROC CHAR(8),
                                   OUT OUT_SQL_SQLCODE INTEGER,
                                   OUT OUT_SQL_MESSAGE VARCHAR(60) )
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC PRAXIS.SQP05069

BEGIN
	/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
    ++ HISTORIAL DE CAMBIOS
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ++  DEV     CODE    DATE        DESCRIPCION                                        
    ++  VHO     202300  14/07/2023  Creacion de SP
	++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
	DECLARE VL_SQLCODE INTEGER DEFAULT 0 ;
	DECLARE VL_QRYSQL , VL_QRYSQL_1 VARCHAR ( 4000 ) ;
	DECLARE VL_EOF , VL_NHOT , VL_DIADELASEMANA INTEGER DEFAULT 0 ;
	DECLARE VL_A4469PDATE CHAR ( 8 ) ;
	DECLARE VL_A4469PDATE_1 VARCHAR ( 15 ) ;
	DECLARE VL_FOUND , VL_FLAG CHAR ( 1 ) ;
	DECLARE VL_LABEL , VL_LABEL1 , VL_LABEL2 , VL_LABEL3 , VL_LABEL4 , VL_LABEL5 , VL_LABEL6 , VL_LABEL7 CHAR ( 1 ) ;
	DECLARE VL_COUNTRY VARCHAR ( 40 ) ;
	DECLARE VL_A4469STATU , VL_A4469IDATE VARCHAR ( 150 ) ;
	DECLARE VL_A4469TSALE , VL_A4469TEXCH , VL_A4469TRFND , VL_A4469TMEMO , VL_A4469TVOID INT ;
	DECLARE VL_PDATE VARCHAR ( 12 ) ;
	DECLARE VL_COUNT , VL_COUNT1 INT ;
	
	DECLARE VL_SQLQRY VARCHAR ( 2000 ) DEFAULT '' ;	
	DECLARE CURQRY CURSOR FOR STMTQRY ;
	
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION	
	
	DECLARE GLOBAL TEMPORARY TABLE SESSION . TEMP99 (
		NHOT INT ,
		COUNTRY VARCHAR ( 60 ) ,
		COUNTRY_CODE VARCHAR ( 3 ) ,
		CURR CHAR ( 3 ) ,		
		--		
		PRDA1 CHAR ( 8 ) , PRDA1_ VARCHAR ( 15 ) , STATUS1 VARCHAR ( 10 ) , ISSUDT1 VARCHAR ( 150 ) ,		
		SALE1 INT , EXCH1 INT , RFND1 INT , MEMO1 INT , VOID1 INT , LABEL1 CHAR ( 1 ) , FLG1 CHAR ( 1 ) DEFAULT ''
	) WITH REPLACE ON COMMIT PRESERVE ROWS NOT LOGGED ;
	
	SET VL_SQLCODE = SQLCODE ;
	SET OUT_SQL_SQLCODE = '0' ;
	SET OUT_SQL_MESSAGE = 'execution was successful.' ;
	
	-- Genera 1 dias desde una "Fecha inicial". 
	SET VL_A4469PDATE = VP_FPROC ;
	SET VL_EOF = 0 ;
	SET VL_FOUND = 'N' ;
		
	WHILE ( VL_EOF < 1 ) DO		
		SET VL_EOF = VL_EOF + 1 ;				
		SET VL_A4469PDATE_1 = PRAXIS . FN_GET_DATENAME ( VL_A4469PDATE ) ;				
		-- a SPANISH
		SET VL_A4469PDATE_1 = (
		CASE VL_A4469PDATE_1
	WHEN 'Sunday' THEN 'Domingo'
	WHEN 'Monday' THEN 'Lunes'
	WHEN 'Tuesday' THEN 'Martes'
	WHEN 'Wednesday' THEN 'Miércoles'
	WHEN 'Thursday' THEN 'Jueves'
	WHEN 'Friday' THEN 'Viernes'
	WHEN 'Saturday' THEN 'Sábado'
	END ) ;
								
		
		-- SELECT DAYOFWEEK(DATE( substring('20230308',1,4) ||'-'||substring('20230308',5,2) ||'-'|| substring('20230308',7,2))) FROM SYSIBM.SYSDUMMY1
		-- SELECT MOD(DAYOFWEEK(DATE( substring('20230308',1,4)||'-'||substring('20230308',5,2) ||'-'|| substring('20230308',7,2) )) + 5, 7) + 1 FROM SYSIBM.SYSDUMMY1	
		-- Semana empieza de Domingo	
		SET VL_DIADELASEMANA = DAYOFWEEK ( DATE ( SUBSTRING ( VL_A4469PDATE , 1 , 4 ) || '-' || SUBSTRING ( VL_A4469PDATE , 5 , 2 ) || '-' || SUBSTRING ( VL_A4469PDATE , 7 , 2 ) ) ) ; -- FROM SYSIBM.SYSDUMMY1;
		-- Semana empieza de LUNES	
		-- SET vl_DiaDeLaSemana =  MOD(DAYOFWEEK(DATE( substring(VL_A4469PDATE,1,4)||'-'||substring(VL_A4469PDATE,5,2) ||'-'|| substring(VL_A4469PDATE,7,2) )) + 5, 7) + 1; -- FROM SYSIBM.SYSDUMMY1;					
				
		SET VL_NHOT = 0 ;
		RW0 : FOR RW0_ AS RW0__ CURSOR FOR
		SELECT A4491FUENT , A4491PAIS , A4491MDA , A4491LUN , A4491MAR , A4491MIE , A4491JUE , A4491VIE , A4491SAB , A4491DOM , A4491FLG
		FROM PRAXIS . A4491
		WHERE	A4491CCUST = VP_CCUST
		ORDER BY A4491FUENT , A4491PAIS		
		DO		
							
			SET VL_COUNTRY = '' ;
			IF	TRIM ( RW0 . A4491PAIS ) <> '' THEN	
				SELECT A3152NPAIS INTO VL_COUNTRY FROM PRAXIS . A3152
				WHERE A3152CPAIS = RW0 . A4491PAIS AND A3152CPAIS <> ''
				FETCH FIRST 1 ROWS ONLY ;
			END IF ;	
									
			IF ( TRIM ( VL_COUNTRY ) = '' ) THEN
				SET VL_COUNTRY = RW0 . A4491FUENT ;
			END IF ;			
			SET VL_FOUND = 'S' ;
			SET VL_NHOT = VL_NHOT + 1 ;
			
			-- INSERT INTO PRAXIS.qry_log1 VALUES('VL_COUNTRY:' || VL_COUNTRY);
						
			-- INFORMACION DE VENTAS(DELIVERY)
			SET ( VL_A4469STATU , VL_A4469IDATE , VL_A4469TSALE , VL_A4469TEXCH , VL_A4469TRFND , VL_A4469TMEMO , VL_A4469TVOID ) = ( '' , '' , 0 , 0 , 0 , 0 , 0 ) ;
			IF A4491FUENT = 'BSP' THEN			
				SELECT A4469STATU , A4469IDATE , A4469TSALE , A4469TEXCH , A4469TRFND , A4469TMEMO , A4469TVOID
				INTO VL_A4469STATU , VL_A4469IDATE , VL_A4469TSALE , VL_A4469TEXCH , VL_A4469TRFND , VL_A4469TMEMO , VL_A4469TVOID
				FROM PRAXIS . A4469
				WHERE A4469CCUST = '139' AND A4469PDATE = VL_A4469PDATE AND A4469CDPAI = A4491PAIS AND A4469CURCY = A4491MDA ;
			ELSE
				SELECT A4469STATU , A4469IDATE , A4469TSALE , A4469TEXCH , A4469TRFND , A4469TMEMO , A4469TVOID
				INTO VL_A4469STATU , VL_A4469IDATE , VL_A4469TSALE , VL_A4469TEXCH , VL_A4469TRFND , VL_A4469TMEMO , VL_A4469TVOID
				FROM PRAXIS . A4469
				WHERE A4469CCUST = '139' AND A4469PDATE = VL_A4469PDATE AND A4469SOURC = A4491FUENT ;				
			END IF ;	
			
			
			--------------------------------------------------------------
			
			-- DIA 1			
			IF VL_DIADELASEMANA = 1 THEN
				SET VL_LABEL = '' ;
				IF A4491DOM = 'S' AND VL_A4469STATU = '' THEN
					SET VL_LABEL = 'R' ;
				END IF ;
				IF A4491DOM = 'N' THEN
					SET VL_LABEL = 'A' ;
				END IF ;				
				IF A4491COUNTRY_CODE = 'VE' THEN
			        SET VL_LABEL = 'A' ;
			    END IF ;
			END IF ;
			
			-- DIA 2			
			IF VL_DIADELASEMANA = 2 THEN
				SET VL_LABEL = '' ;
				IF A4491LUN = 'S' AND VL_A4469STATU = '' THEN
					SET VL_LABEL = 'R' ;
				END IF ;
				IF A4491LUN = 'N' THEN
					SET VL_LABEL = 'A' ;
				END IF ;				
			END IF ;
			
			-- DIA 3			
			IF VL_DIADELASEMANA = 3 THEN
				SET VL_LABEL = '' ;
				IF A4491MAR = 'S' AND VL_A4469STATU = '' THEN
					SET VL_LABEL = 'R' ;
				END IF ;
				IF A4491MAR = 'N' THEN
					SET VL_LABEL = 'A' ;
				END IF ;	
				IF A4491FUENT = 'ARC' THEN
					SET VL_LABEL = 'A' ;
				END IF ;
			END IF ;
			-- DIA 4			
			IF VL_DIADELASEMANA = 4 THEN
				SET VL_LABEL = '' ;
				IF A4491MIE = 'S' AND VL_A4469STATU = '' THEN
					SET VL_LABEL = 'R' ;
				END IF ;
				IF A4491MIE = 'N' THEN
					SET VL_LABEL = 'A' ;
				END IF ;	
			END IF ;
			-- DIA 5			
			IF VL_DIADELASEMANA = 5 THEN
				SET VL_LABEL = '' ;
				IF A4491JUE = 'S' AND VL_A4469STATU = '' THEN
					SET VL_LABEL = 'R' ;
				END IF ;
				IF A4491JUE = 'N' THEN
					SET VL_LABEL = 'A' ;
				END IF ;	
			END IF ;
			-- DIA 6			
			IF VL_DIADELASEMANA = 6 THEN
				SET VL_LABEL = '' ;
				IF A4491VIE = 'S' AND VL_A4469STATU = '' THEN
					SET VL_LABEL = 'R' ;
				END IF ;
				IF A4491VIE = 'N' THEN
					SET VL_LABEL = 'A' ;
				END IF ;					
			END IF ;			
			-- DIA7			
			IF VL_DIADELASEMANA = 7 THEN
				SET VL_LABEL = '' ;
				IF A4491SAB = 'S' AND VL_A4469STATU = '' THEN
					SET VL_LABEL = 'R' ;
				END IF ;
				IF A4491SAB = 'N' THEN
					SET VL_LABEL = 'A' ;
				END IF ;	
				IF A4491PAIS = 'VE' THEN
			        SET VL_LABEL = 'A' ;
			    END IF ;
			END IF ;
						
			SET VL_QRYSQL = 'INSERT INTO SESSION.TEMP99 ( NHOT, COUNTRY, COUNTRY_CODE, CURR, ' ;
			SET VL_QRYSQL = VL_QRYSQL || 'PRDA' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'PRDA' || VL_EOF || '_,' ;
			SET VL_QRYSQL = VL_QRYSQL || 'STATUS' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'ISSUDT' || VL_EOF || ',' ;
			
			SET VL_QRYSQL = VL_QRYSQL || 'SALE' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'EXCH' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'RFND' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'MEMO' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'VOID' || VL_EOF || ',' ;
			SET VL_QRYSQL = VL_QRYSQL || 'FLG' || VL_EOF || ',' ; -- new				
			SET VL_QRYSQL = VL_QRYSQL || 'LABEL' || VL_EOF ;		
			SET VL_QRYSQL = VL_QRYSQL || ' )' ;
			
			SET VL_QRYSQL = VL_QRYSQL || ' VALUES (''' ;
		SET VL_QRYSQL = VL_QRYSQL || VL_NHOT || ''',''' || TRIM ( VL_COUNTRY ) || ''',''' || A4491PAIS || ''',''' || A4491MDA || ''',''' ;
			SET VL_QRYSQL = VL_QRYSQL || VL_A4469PDATE || ''',''' || VL_A4469PDATE_1 || ''',''' || TRIM ( VL_A4469STATU ) || ''',''' || TRIM ( VL_A4469IDATE ) || ''',''' ;
			SET VL_QRYSQL = VL_QRYSQL || VL_A4469TSALE || ''',''' || VL_A4469TEXCH || ''',''' || VL_A4469TRFND || ''',''' || VL_A4469TMEMO || ''',''' || VL_A4469TVOID || ''',''' || A4491FLG || ''',''' ;
			SET VL_QRYSQL = VL_QRYSQL || VL_LABEL || ''')' ;
									
--			SET VL_QRYSQL = 
--			CASE vl_DiaDeLaSemana 
--				WHEN 1 THEN VL_QRYSQL || VL_LABEL1 ||''')'
--				WHEN 2 THEN VL_QRYSQL || VL_LABEL2 ||''')'
--				WHEN 3 THEN VL_QRYSQL || VL_LABEL3 ||''')'
--				WHEN 4 THEN VL_QRYSQL || VL_LABEL4 ||''')'
--				WHEN 5 THEN VL_QRYSQL || VL_LABEL5 ||''')'
--				WHEN 6 THEN VL_QRYSQL || VL_LABEL6 ||''')'
--				WHEN 7 THEN VL_QRYSQL || VL_LABEL7 ||''')'
--			END;
			
			-- INSERT INTO PRAXIS.qry_log1 VALUES(VL_QRYSQL);
			
			SET VL_FLAG = 'N' ;
			IF A4491FUENT = 'BSP' THEN		
				SELECT 'S' INTO VL_FLAG FROM SESSION . TEMP99 WHERE COUNTRY_CODE = A4491PAIS AND CURR = A4491MDA ;
			ELSE
				SELECT 'S' INTO VL_FLAG FROM SESSION . TEMP99 WHERE COUNTRY = A4491FUENT ; -- ASR/ARC
			END IF ;
			
			IF IFNULL ( VL_FLAG , 'N' ) = 'N' THEN				
				EXECUTE IMMEDIATE VL_QRYSQL ; -- INSERT
			ELSE
				SET VL_QRYSQL_1 = 'UPDATE SESSION.temp99 SET ' ;	
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' NHOT=''' || VL_NHOT || ''',' ;		
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' PRDA' || VL_EOF || '=''' || VL_A4469PDATE || ''', ' ;									
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' PRDA' || VL_EOF || '_ =''' || VL_A4469PDATE_1 || ''', ' ;	
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' STATUS' || VL_EOF || '=''' || TRIM ( VL_A4469STATU ) || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' ISSUDT' || VL_EOF || '=''' || TRIM ( VL_A4469IDATE ) || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' SALE' || VL_EOF || '=''' || VL_A4469TSALE || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' EXCH' || VL_EOF || '=''' || VL_A4469TEXCH || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' RFND' || VL_EOF || '=''' || VL_A4469TRFND || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' MEMO' || VL_EOF || '=''' || VL_A4469TMEMO || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' VOID' || VL_EOF || '=''' || VL_A4469TVOID || ''', ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' LABEL' || VL_EOF || '=''' || VL_LABEL || ''' ' ;
				
--				CASE vl_DiaDeLaSemana 
--					WHEN 1 THEN VL_QRYSQL_1 || ' LABEL'||VL_EOF||'=''' || VL_LABEL1 || ''' '
--					WHEN 2 THEN VL_QRYSQL_1 || ' LABEL'||VL_EOF||'=''' || VL_LABEL2 || ''' ' 
--					WHEN 3 THEN VL_QRYSQL_1 || ' LABEL'||VL_EOF||'=''' || VL_LABEL3 || ''' '
--					WHEN 4 THEN VL_QRYSQL_1 || ' LABEL'||VL_EOF||'=''' || VL_LABEL4 || ''' '
--					WHEN 5 THEN VL_QRYSQL_1 || ' LABEL'||VL_EOF||'=''' || VL_LABEL5 || ''' ' 
--					WHEN 6 THEN VL_QRYSQL_1 || ' LABEL'||VL_EOF||'=''' || VL_LABEL6 || ''' '
--					WHEN 7 THEN VL_QRYSQL_1 || ' LABEL'||VL_EOF||'=''' || VL_LABEL7 || ''' '
--				END;
				-- new
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' ,FLG' || VL_EOF || '=''' || A4491FLG || ''' ' ;
				
--				CASE vl_DiaDeLaSemana 
--					WHEN 1 THEN VL_QRYSQL_1 || ' ,FLG'||VL_EOF||'=''' || A4491FLG || ''' '
--					WHEN 2 THEN VL_QRYSQL_1 || ' ,FLG'||VL_EOF||'=''' || A4491FLG || ''' ' 
--					WHEN 3 THEN VL_QRYSQL_1 || ' ,FLG'||VL_EOF||'=''' || A4491FLG || ''' '
--					WHEN 4 THEN VL_QRYSQL_1 || ' ,FLG'||VL_EOF||'=''' || A4491FLG || ''' '
--					WHEN 5 THEN VL_QRYSQL_1 || ' ,FLG'||VL_EOF||'=''' || A4491FLG || ''' ' 
--					WHEN 6 THEN VL_QRYSQL_1 || ' ,FLG'||VL_EOF||'=''' || A4491FLG || ''' '
--					WHEN 7 THEN VL_QRYSQL_1 || ' ,FLG'||VL_EOF||'=''' || A4491FLG || ''' '
--				END;
												
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' WHERE COUNTRY_CODE=''' || A4491PAIS || ''' ' ;
				SET VL_QRYSQL_1 = VL_QRYSQL_1 || ' AND CURR='''	|| A4491MDA	|| ''' ' ;									
				-- INSERT INTO PRAXIS.qry_log1 VALUES(VL_QRYSQL_1);
				EXECUTE IMMEDIATE VL_QRYSQL_1 ;								
			END IF ;	
								
		END FOR RW0 ;
		
		-- ADD INTERVAL 1 DAY		
		SET VL_PDATE = DATE ( DATE ( SUBSTR ( VL_A4469PDATE , 1 , 4 ) || '-' || SUBSTR ( VL_A4469PDATE , 5 , 2 ) || '-' || SUBSTR ( VL_A4469PDATE , 7 , 2 ) ) ) + 1 DAYS ;	
		SET VL_A4469PDATE = YEAR ( VL_PDATE ) || LPAD ( MONTH ( VL_PDATE ) , 2 , '0' ) || LPAD ( DAY ( VL_PDATE ) , 2 , '0' ) ;
			
	END WHILE ;
		
		
	RW1 : FOR RW1_ AS RW1__ CURSOR FOR
	SELECT * FROM SESSION . TEMP99
	WHERE COUNTRY_CODE IN ( 'AR' , 'BO' , 'CL' , 'PH' , 'PY' , 'RO' , 'RS' )	
	DO	
		-- MARCA:
		-- ROJO=HOT NO REPORTADO)	
		-- AZUL=ARCHIVO DE FIN DE SEMANA      
		SET VL_COUNT = 0 ;			
		SELECT COUNT ( 0 ) INTO VL_COUNT FROM SESSION . TEMP99 WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE AND STATUS1 = '' ;
		IF ( VL_COUNT = 2 ) THEN
			UPDATE SESSION . TEMP99 SET LABEL1 = 'R' WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE AND LABEL1 <> 'A' ;			
		ELSE
			UPDATE SESSION . TEMP99 SET LABEL1 = '' WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE AND LABEL1 <> 'A' ;			
		END IF ;
		
		-- MARCA PARA REGISTRO ADICIONAL(NO ENTRA AL CONTEO DE HOT) 
		SET VL_COUNT = 0 ;
		SELECT COUNT ( 0 ) INTO VL_COUNT FROM SESSION . TEMP99 WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE AND FLG1 = '' ;
		IF ( VL_COUNT = 2 ) THEN
			UPDATE SESSION . TEMP99 SET FLG1 = 'Y'
			WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE AND NHOT IN ( SELECT MAX ( NHOT ) FROM SESSION . TEMP99 WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE ) ;
		ELSE		
			UPDATE SESSION . TEMP99 SET FLG1 = '' WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE ;
			UPDATE SESSION . TEMP99 SET FLG1 = 'Y'
			WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE AND NHOT IN ( SELECT MAX ( NHOT ) FROM SESSION . TEMP99 WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE AND STATUS1 = '' ) ;
			--
			SET VL_COUNT1 = 0 ;
			SELECT COUNT ( 0 ) INTO VL_COUNT1 FROM SESSION . TEMP99 WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE AND FLG1 = '' ;
			IF ( VL_COUNT1 = 0 ) THEN
				UPDATE SESSION . TEMP99 SET FLG1 = 'Y' WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE AND NHOT IN ( SELECT MAX ( NHOT ) FROM SESSION . TEMP99 WHERE COUNTRY_CODE = RW1 . COUNTRY_CODE ) ;
			END IF ;
		END IF ;
							
	END FOR RW1 ;
	
	DELETE FROM PRAXIS . A4493 WHERE A4493CCUST = VP_CCUST AND A4493PRDA = VP_FPROC ;
	
	INSERT INTO PRAXIS . A4493 ( A4493CCUST , A4493PRDA , A4493HOTN , A4493FUENT , A4493PAIS , A4493MDA , A4493PAISD ,
	A4493PRDD , A4493STAT , A4493ISSUD , A4493SALE , A4493EXCH , A4493RFND , A4493MEMO , A4493VOID , A4493LABEL , A4493FLAG )	
	SELECT '139' , PRDA1 , NHOT , ( CASE WHEN COUNTRY IN ( 'ARC' , 'ASR' ) THEN COUNTRY ELSE 'BSP' END ) FUENTE , COUNTRY_CODE , CURR , COUNTRY , PRDA1_ , STATUS1 , ISSUDT1 , SALE1 , EXCH1 , RFND1 , MEMO1 , VOID1 , LABEL1 , FLG1
	FROM (
		SELECT ROW_NUMBER ( ) OVER ( ORDER BY COUNTRY_CODE ) AS NHOT , COUNTRY , COUNTRY_CODE , CURR , PRDA1 , PRDA1_ ,
		STATUS1 , ISSUDT1 , SALE1 , EXCH1 , RFND1 , MEMO1 , VOID1 , LABEL1 , FLG1
		FROM SESSION . TEMP99
	) AS W ;
	
		IF ( VL_SQLCODE = 0 ) THEN	SET OUT_SQL_MESSAGE = 'execution was successful.' ; END IF ;
		-- IF ( VL_SQLCODE > 0 ) THEN	SET OUT_SQL_MESSAGE = 'execution was successful with a warning.' ;END IF ;
		IF ( VL_SQLCODE < 0 ) THEN	SET OUT_SQL_MESSAGE = 'execution was not successful.' ; END IF ;
		IF VL_SQLCODE <> 0 THEN
			SET OUT_SQL_SQLCODE = '0' ;
		END IF ;
		
	END

GRANT ALL ON PROCEDURE PRAXIS.SQP05069 TO PUBLIC 
