SELECT * 
FROM PRAXIS.A003 
WHERE A003CTANEG = ''
 AND A003CTACTO = ''
 AND A003CTAUBC = ''
 AND A003TIPO='ARC'
  --AND A003AREA = ''
 
 
 
 SELECT * FROM LIBMIATEC.A006 
 
 
 
 SELECT * FROM PRAXIS.INF054 
 
 
SELECT COLUMN_NAME
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'PRAXIS'
AND TABLE_NAME = 'INF054';

CALL PRAXIS.SPCL3050('139');





SELECT ROUTINE_SCHEMA, ROUTINE_NAME
FROM QSYS2.SYSROUTINES
WHERE ROUTINE_NAME IN ('SPCL3050','SPRUT1147');


SELECT ROUTINE_SCHEMA, ROUTINE_NAME
FROM QSYS2.SYSROUTINES
WHERE ROUTINE_NAME = 'SPRUT1147';