

-----INICIAL-------

CREATE OR REPLACE PROCEDURE PRAXISMP.MPS295 ( IN IN_IDCONT VARCHAR(25) )
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC PRAXISMP.MPS295

BEGIN
/*
     * Liquidaciones Credomatic
     */
DECLARE V_SQL VARCHAR ( 8000 ) ;
DECLARE V_WHERE VARCHAR ( 5000 ) DEFAULT '' ;

-- Cursor 
DECLARE CURQRY01 CURSOR WITH RETURN FOR STMTQRY01 ;

SET V_SQL = '
		    
		SELECT TBL.*,
		((CASE WHEN SCURRENCY = MDA_VTA THEN TBL.SVFOP ELSE TBL.IMPORTEPAG END)- TBL.SUMA_VTA) SUM_DIFF FROM (
		SELECT BANDOC,SCARDN,SAUTHOC,SDATE,SVFOP,SCURRENCY,IMPORTEPAG,MONEDAPAGO,SAGENT,MERCHNC,STVAL,GENCON,
		IFNULL((SELECT SUM(CASE WHEN B.TDOC = ''S'' THEN ABS(B.SVFOP) ELSE ABS(B.SVFOP) * -1 END) 
		FROM PRAXISMP.MPF100 B WHERE B.DATEC = A.DATEC AND B.TRANC = A.TRANC AND B.CODPRO = A.CODPRO),0) SUMA_VTA,
		IFNULL((SELECT MAX(SCURRENCY) FROM PRAXISMP.MPF100 B WHERE B.DATEC = A.DATEC AND B.TRANC = A.TRANC AND B.CODPRO = A.CODPRO),'''') MDA_VTA,
		(SELECT COUNT(0) FROM PRAXISMP.MPF100 B WHERE B.DATEC = A.DATEC AND B.TRANC = A.TRANC AND B.CODPRO = A.CODPRO) QTY_TKT
		FROM PRAXISMP.MPF101 A
		WHERE IDCONT=''' || IN_IDCONT || '''
		AND TDOC=''S'' 
		AND TDOCORG='''' 
		AND STVAL IN (''1'',''5'')
		) AS TBL 
		ORDER BY SUM_DIFF DESC, GENCON
		' ;


SET V_SQL = REPLACE ( V_SQL , '{WHERE}' , V_WHERE ) ;

PREPARE STMTQRY01 FROM V_SQL ;
OPEN CURQRY01 ;
END




/***************************************************************************************************************************************************************************************************/


--CALL PRAXISMP.MPS295('202REGWP12509250919132924')