-- TABLA 
SELECT*FROM PRAXIS . A1820


-- revisar longitud de campos de la tabla
SELECT COLUMN_NAME, LENGTH
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'PRAXIS'
AND TABLE_NAME = 'A1820'
AND COLUMN_NAME IN ('A1820CECO','A1820CTA');



-- CAMBIAR LONGITUD DE CAMPOS DE TABLA
ALTER TABLE PRAXIS.A1820
ALTER COLUMN A1820CECO SET DATA TYPE VARCHAR(7);


ALTER TABLE PRAXIS.A1820
ALTER COLUMN A1820CTA SET DATA TYPE VARCHAR(6);