CREATE OR REPLACE PROCEDURE PRAXIS.SQP04221 ( IN IN_CCUST VARCHAR(3),
                                   IN IN_FILTRO VARCHAR(20),
                                   IN IN_CLIENTE VARCHAR(15),
                                   IN IN_TARJETA VARCHAR(20),
                                   IN IN_CUENTA VARCHAR(6),
                                   IN IN_SUBCUENTA VARCHAR(5),
                                   INOUT IO_PAGNUM INTEGER,
                                   INOUT IO_PAGROW INTEGER,
                                   INOUT IO_TOTPAG INTEGER,
                                   INOUT IO_TOTROW INTEGER,
                                   IN IN_MODO CHAR(1) )
	RESULT SETS 2
	LANGUAGE SQL
	SPECIFIC PRAXIS.SQP04221

BEGIN DECLARE CURQRY_COUNT CURSOR FOR
SELECT COUNT ( 1 ) FROM PRAXIS . A1820
WHERE A1820CCUST = IN_CCUST
AND ( A1820TIPO = IN_FILTRO OR IN_FILTRO = '' )
AND ( A1820CLIEN LIKE '%' CONCAT IN_CLIENTE CONCAT '%' OR IN_CLIENTE = '' )
AND ( A1820TCUAT LIKE '%' CONCAT IN_TARJETA CONCAT '%' OR IN_TARJETA = '' )
AND ( A1820CTA LIKE '%' CONCAT IN_CUENTA CONCAT '%' OR IN_CUENTA = '' )
AND ( A1820SCTA LIKE '%' CONCAT IN_SUBCUENTA CONCAT '%' OR IN_SUBCUENTA = '' )
AND ( A1820MODO = IN_MODO OR IN_MODO = 'A' ) ;

DECLARE CURQRY01 CURSOR FOR
SELECT * FROM ( SELECT ROW_NUMBER ( ) OVER ( ) AS RN , T . *
FROM ( SELECT A1820CCUST , A1820TCUAT , A1820DESCR , A1820CLIEN , A1820DIREC , A1820TIPO , A1820DOCU , A1820CIA , A1820UNID , A1820CECO ,
A1820UBI , A1820CTA , A1820SCTA , A1820EQUI , A1820ICIA , A1820FINI , A1820FFIN , A1820REGIS , A1820FREGI , A1820HREGI , A1820REGVI ,
A1820FREVI , A1820HREVI , A1820MODO FROM PRAXIS . A1820
WHERE A1820CCUST = IN_CCUST
AND ( A1820TIPO = IN_FILTRO OR IN_FILTRO = '' )
AND ( A1820CLIEN LIKE '%' CONCAT IN_CLIENTE CONCAT '%' OR IN_CLIENTE = '' )
AND ( A1820TCUAT LIKE '%' CONCAT IN_TARJETA CONCAT '%' OR IN_TARJETA = '' )
AND ( A1820CTA LIKE '%' CONCAT IN_CUENTA CONCAT '%' OR IN_CUENTA = '' )
AND ( A1820SCTA LIKE '%' CONCAT IN_SUBCUENTA CONCAT '%' OR IN_SUBCUENTA = '' )
AND ( A1820MODO = IN_MODO OR IN_MODO = 'A' ) ) AS T ) AS RS WHERE RS . RN >= IO_PAGNUM
AND ( ( IO_PAGNUM - RS . RN + IO_PAGROW ) > 0 OR IO_PAGROW = - 1 )
ORDER BY A1820TCUAT ;
OPEN CURQRY01 ; OPEN CURQRY_COUNT ;
FETCH CURQRY_COUNT INTO IO_TOTROW ;
END