


CREATE OR REPLACE PROCEDURE PRAXISMP.SQP05016 ()

	RESULT SETS 5
	LANGUAGE SQL
	SPECIFIC PRAXISMP.SQP05016

BEGIN

	/*******************************************************************************************************
 	* 10/10/2025 CREATE PROGRAM DP
 	* TITLE PROGRAM: Filters Complement
 	*
 	* DEFINITIONS:
 	-
 	*********************************************************************************************************/

	-- PAISES
	DECLARE COUNTRIES CURSOR FOR
		SELECT DISTINCT A3152CPAIS CODE , A3152NPAIS PAIS , A3152CPAIS || '-' || A3152NPAIS NAME , A3152NREGI AREA
		FROM PRAXIS . A3152
		WHERE A3152CPAIS <> '' ORDER BY CODE ;

	-- CERRORS
	DECLARE CERRORS CURSOR FOR
		SELECT X.*
		FROM (
			SELECT A4480COD AS CODE, TRIM(A4480COD) ||'-'|| TRIM (A4480DES) AS DESCRIPTION, 1 AS POSITION
			FROM PRAXISMP.A4480 WHERE A4480STS = 'A' AND A4480TIP = '01'
		 ) X
		 ORDER BY X.POSITION , X.CODE ;
--
	DECLARE STVAL_VS_SALES CURSOR FOR
		SELECT X.*
		FROM (
			SELECT 'X' AS STVAL, 'All' AS DESCRIPTION, 0 AS POSITION FROM SYSIBM.SYSDUMMY1
				UNION ALL
			SELECT '' AS STVAL, 'Pending' AS DESCRIPTION, 1 AS POSITION FROM SYSIBM.SYSDUMMY1
				UNION ALL
			SELECT A4451KEY3 AS STVAL, A4451DESC1 AS DESCRIPTION, 2 AS POSITION
			FROM PRAXISMP.A4451 WHERE A4451KEY1 = 'PK' AND A4451KEY2 = 'STVAL' AND A4451FECH2 = '1'
		) X
		ORDER BY X.POSITION, X.STVAL ;
	
	-- PROCESADOR INSUMOS
	
	DECLARE PROCESSORINSUMO CURSOR FOR
		SELECT X.*
		FROM (
		    -- Opción All
		    SELECT '' AS CODE, 'All' AS DESCRIPTION, 0 AS POSITION
		    FROM SYSIBM.SYSDUMMY1
		
		    UNION ALL
		
		    -- Procesadores únicos con DESCRIPTION formateada
		    SELECT DISTINCT
		           TRIM(A4791PROCE) AS CODE,
		           UPPER(SUBSTRING(TRIM(A4791PROCE),1,1)) ||
		           LOWER(REPLACE(SUBSTRING(TRIM(A4791PROCE),2), '_',' ')) AS DESCRIPTION,
		           1 AS POSITION
		    FROM PRAXISMP.A4791
		    WHERE TRIM(A4791PROCE) <> ''
		) X
		ORDER BY X.POSITION, X.CODE;




	
	-- PROCESADOR MATCH
	DECLARE PROCESSORMATCH CURSOR FOR
		SELECT X.*
		FROM (
		    SELECT A4451KEY2,
		           A4451KEY3,
		           A4451DESC1,
		           A4451DESC2
		    FROM PRAXISMP.A4451
		    WHERE A4451KEY1 = 'PR'
		    AND A4451STS = '1'
		) X
		ORDER BY X.A4451KEY3;


	OPEN COUNTRIES ;
	OPEN CERRORS ;
	OPEN STVAL_VS_SALES ;
	OPEN PROCESSORINSUMO;
	OPEN PROCESSORMATCH;
END




GRANT ALL ON PROCEDURE PRAXISMP.SQP05016 TO PUBLIC;




-- CALL PRAXISMP.SQP05016 () ;
