

CREATE OR REPLACE PROCEDURE PRAXISMP.SQP05697 ( IN IN_PRDA_FROM VARCHAR(8),
                                     IN IN_PRDA_TO VARCHAR(8),
                                     IN IN_PNR VARCHAR(6),
                                     IN IN_TICKET VARCHAR(13),
                                     IN IN_CARDN1 VARCHAR(6),
                                     IN IN_CARDN2 VARCHAR(4),
                                     IN IN_AUTH VARCHAR(6),
                                     IN IN_STATUS VARCHAR(18),
                                     IN IN_TOTAL VARCHAR(20),
                                     IN IN_PROCINSUMO VARCHAR(20),
                                     IN IN_PROCMATCH VARCHAR(10),
                                     INOUT IO_PAGNUM INTEGER ,
                                     INOUT IO_PAGROW INTEGER ,
                                     INOUT IO_TOTPAG INTEGER ,
                                     INOUT IO_TOTROW INTEGER )
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC PRAXISMP.SQP05697

BEGIN
	/*******************************************************************************************************
 	* 02/10/2025 CREATE PROGRAM YD
 	* TITLE PROGRAM: Search DEUNA
 	*
 	* DEFINITIONS:
 	-
 	*********************************************************************************************************/


	DECLARE V_SQL VARCHAR ( 10000 ) ;
	DECLARE PAGROWINIT INTEGER ;
	DECLARE SQLPAG01 VARCHAR ( 10000 ) ;
	DECLARE CURQRY01 CURSOR FOR STMTQRY01 ;

	SET V_SQL = '
		SELECT ROW_NUMBER() OVER (ORDER BY X.A4791PRDA) AS RN, X.*
			, IFNULL( CT.STVAL_DESCRIPTION , '''' ) AS STVAL_DESCRIPTION
			, IFNULL( CP.PROSQ_DESCRIPTION , '''' ) AS PROSQ_DESCRIPTION
		FROM PRAXISMP.A4791 X
	        LEFT JOIN (
					SELECT A4451KEY3 AS STVAL, A4451DESC2 AS STVAL_DESCRIPTION
						FROM PRAXISMP.A4451 WHERE A4451KEY1 = ''PK'' AND A4451KEY2 = ''STVAL'' AND A4451STS = ''1''
						UNION ALL
						SELECT '''' AS STVAL , ''Pending'' AS STVAL_DESCRIPTION FROM SYSIBM.SYSDUMMY1
			) AS CT ON CT.STVAL = X.A4791STVAL
	        LEFT JOIN (
	            	SELECT DISTINCT A4451KEY2 AS PROSQ, A4451DESC1 AS PROSQ_DESCRIPTION
	            	FROM PRAXISMP.A4451 WHERE A4451KEY1 = ''PR'' AND A4451STS = ''1''
			) AS CP ON CP.PROSQ = X.A4791PROSQ
		WHERE A4791PRDA BETWEEN  ''' || IN_PRDA_FROM || ''' AND ''' || IN_PRDA_TO || '''
		AND A4791PNR = CASE WHEN IFNULL ( ''' || UPPER ( IN_PNR ) || ''' , '''') = '''' THEN A4791PNR ELSE ''' || UPPER ( IN_PNR ) || ''' END
		AND LEFT ( A4791CARDN , 6 ) = CASE WHEN IFNULL ( ''' || IN_CARDN1 || ''' , '''') = '''' THEN LEFT ( A4791CARDN , 6 ) ELSE ''' || IN_CARDN1 || ''' END
		AND RIGHT ( TRIM ( A4791CARDN ) , 4 ) = CASE WHEN IFNULL ( ''' || IN_CARDN2 || ''' , '''') = '''' THEN RIGHT ( TRIM ( A4791CARDN ) , 4 ) ELSE ''' || IN_CARDN2 || ''' END
		AND A4791AUTH = CASE WHEN IFNULL ( ''' || IN_AUTH || ''' , '''') = '''' THEN A4791AUTH ELSE ''' || IN_AUTH || ''' END
		AND A4791STATU = CASE WHEN IFNULL ( ''' || IN_STATUS || ''' , '''') = '''' THEN A4791STATU ELSE ''' || IN_STATUS || ''' END
		AND A4791TKT = CASE WHEN IFNULL ( ''' || IN_TICKET || ''' , '''') = '''' THEN A4791TKT ELSE ''' || IN_TICKET || ''' END
		AND A4791PROCE = CASE WHEN IFNULL ( ''' || IN_PROCINSUMO || ''' , '''') = '''' THEN A4791PROCE ELSE ''' || IN_PROCINSUMO || ''' END
		AND A4791PROSQ = CASE WHEN IFNULL ( ''' || IN_PROCMATCH || ''' , '''') = '''' THEN A4791PROSQ ELSE ''' || IN_PROCMATCH || ''' END
	' ;

	 
	IF IO_TOTROW = - 1 THEN
		SET SQLPAG01 = 'SELECT COUNT (1) FROM (' CONCAT V_SQL CONCAT ') ' ;

		PREPARE STMTQRY01 FROM SQLPAG01 ;
		OPEN CURQRY01 ;
		FETCH_LOOP : LOOP FETCH CURQRY01 INTO IO_TOTROW ;
			LEAVE FETCH_LOOP ;
		END LOOP FETCH_LOOP ;
		CLOSE CURQRY01 ;
	END IF ;

	SET IO_PAGNUM = PRAXIS . F0001 ( 'PAGNUM' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_PAGROW = PRAXIS . F0001 ( 'PAGROW' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_TOTPAG = PRAXIS . F0001 ( 'TOTPAG' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_TOTROW = PRAXIS . F0001 ( 'TOTROW' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET PAGROWINIT = PRAXIS . F0001 ( 'PRINIT' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;

	SET SQLPAG01 = 'SELECT * FROM (' CONCAT V_SQL CONCAT ') AS RS WHERE RS.RN > ' CONCAT
	PAGROWINIT CONCAT ' ' ;

	IF IO_PAGROW > 0 THEN
		SET SQLPAG01 = SQLPAG01 CONCAT ' FETCH FIRST ' CONCAT IO_PAGROW CONCAT ' ROWS ONLY' ;
	END IF ;
	
	PREPARE STMTQRY01 FROM SQLPAG01 ;
	OPEN CURQRY01 ;
END




DROP VARIABLE PRAXISMP.TEST_EXECUTE


/*

CREATE OR REPLACE VARIABLE PRAXISMP.TEST_EXECUTE VARCHAR(9000) DEFAULT '';


DROP VARIABLE PRAXISMP.TEST_EXECUTE

CREATE OR REPLACE VARIABLE PRAXISMP.TESTIO_PAGNUM INTEGER DEFAULT 1;
CREATE OR REPLACE VARIABLE PRAXISMP.TESTIO_PAGROW INTEGER DEFAULT 20;
CREATE OR REPLACE VARIABLE PRAXISMP.TESTIO_TOTPAG INTEGER  DEFAULT 0;
CREATE OR REPLACE VARIABLE PRAXISMP.TESTIO_TOTROW INTEGER  DEFAULT 0;

VALUES PRAXISMP.TEST_EXECUTE;
 
SELECT * FROM (
		SELECT ROW_NUMBER() OVER (ORDER BY X.A4791PRDA) AS RN, X.*
			, IFNULL( CT.STVAL_DESCRIPTION , '' ) AS STVAL_DESCRIPTION
			, IFNULL( CP.PROSQ_DESCRIPTION , '' ) AS PROSQ_DESCRIPTION
		FROM PRAXISMP.A4791 X
	        LEFT JOIN (
					SELECT A4451KEY3 AS STVAL, A4451DESC2 AS STVAL_DESCRIPTION
						FROM PRAXISMP.A4451 WHERE A4451KEY1 = 'PK' AND A4451KEY2 = 'STVAL' AND A4451STS = '1'
						UNION ALL
						SELECT '' AS STVAL , 'Pending' AS STVAL_DESCRIPTION FROM SYSIBM.SYSDUMMY1
			) AS CT ON CT.STVAL = X.A4791STVAL
	        LEFT JOIN (
	            	SELECT DISTINCT A4451KEY2 AS PROSQ, A4451DESC1 AS PROSQ_DESCRIPTION
	            	FROM PRAXISMP.A4451 WHERE A4451KEY1 = 'PR' AND A4451STS = '1'
			) AS CP ON CP.PROSQ = X.A4791PROSQ
		WHERE A4791PRDA BETWEEN  '20251020' AND '20251020'
		AND A4791PNR = CASE WHEN IFNULL ( '' , '') = '' THEN A4791PNR ELSE '' END
		AND LEFT ( A4791CARDN , 6 ) = CASE WHEN IFNULL ( '' , '') = '' THEN LEFT ( A4791CARDN , 6 ) ELSE '' END
		AND RIGHT ( TRIM ( A4791CARDN ) , 4 ) = CASE WHEN IFNULL ( '' , '') = '' THEN RIGHT ( TRIM ( A4791CARDN ) , 4 ) ELSE '' END
		AND A4791AUTH = CASE WHEN IFNULL ( '' , '') = '' THEN A4791AUTH ELSE '' END
		AND A4791STATU = CASE WHEN IFNULL ( '' , '') = '' THEN A4791STATU ELSE '' END
		AND A4791TKT = CASE WHEN IFNULL ( '' , '') = '' THEN A4791TKT ELSE '' END
		AND A4791PROCE = CASE WHEN IFNULL ( '' , '') = '' THEN A4791PROCE ELSE '' END
		AND A4791PROSQ = CASE WHEN IFNULL ( '' , '') = 
		
		
CALL PRAXISMP.SQP05697 ( '20251020','20251020','','','','','','','','','',
PRAXISMP.TESTIO_PAGNUM ,
PRAXISMP.TESTIO_PAGROW ,
PRAXISMP.TESTIO_TOTPAG ,
PRAXISMP.TESTIO_TOTROW 
);


                                     IN IN_PNR VARCHAR(6),
                                     IN IN_TICKET VARCHAR(13),
                                     IN IN_CARDN1 VARCHAR(6),
                                     IN IN_CARDN2 VARCHAR(4),
                                     IN IN_AUTH VARCHAR(6),
                                     IN IN_STATUS VARCHAR(18),
                                     IN IN_TOTAL VARCHAR(20),
                                     IN IN_PROCINSUMO VARCHAR(20),
                                     IN IN_PROCMATCH VARCHAR(10),
                                     INOUT IO_PAGNUM INTEGER DEFAULT 1,
                                     INOUT IO_PAGROW INTEGER DEFAULT 20,
                                     INOUT IO_TOTPAG INTEGER DEFAULT 0,
                                     INOUT IO_TOTROW INTEGER DEFAULT 0 )

SELECT ROW_NUMBER() OVER (ORDER BY X.A4791PRDA) AS RN, X.*
			, IFNULL( CT.STVAL_DESCRIPTION , '' ) AS STVAL_DESCRIPTION
			, IFNULL( CP.PROSQ_DESCRIPTION , '' ) AS PROSQ_DESCRIPTION
		FROM PRAXISMP.A4791 X
	        LEFT JOIN (
					SELECT A4451KEY3 AS STVAL, A4451DESC2 AS STVAL_DESCRIPTION
						FROM PRAXISMP.A4451 WHERE A4451KEY1 = ''PK'' AND A4451KEY2 = 'STVAL' AND A4451STS = '1'
						UNION ALL
						SELECT '' AS STVAL , 'Pending' AS STVAL_DESCRIPTION FROM SYSIBM.SYSDUMMY1
			) AS CT ON CT.STVAL = X.A4791STVAL
	        LEFT JOIN (
	            	SELECT DISTINCT A4451KEY2 AS PROSQ, A4451DESC1 AS PROSQ_DESCRIPTION
	            	FROM PRAXISMP.A4451 WHERE A4451KEY1 = ''PR'' AND A4451STS = '1'
			) AS CP ON CP.PROSQ = X.A4791PROSQ
		WHERE A4791PRDA BETWEEN  '20250101' AND '20250102'  ' || IN_PRDA_FROM || ''' AND ''' || IN_PRDA_TO || '''
		AND A4791PNR = CASE WHEN IFNULL ( ''' || UPPER ( IN_PNR ) || ''' , '''') = '''' THEN A4791PNR ELSE ''' || UPPER ( IN_PNR ) || ''' END
		AND LEFT ( A4791CARDN , 6 ) = CASE WHEN IFNULL ( ''' || IN_CARDN1 || ''' , '''') = '''' THEN LEFT ( A4791CARDN , 6 ) ELSE ''' || IN_CARDN1 || ''' END
		AND RIGHT ( TRIM ( A4791CARDN ) , 4 ) = CASE WHEN IFNULL ( ''' || IN_CARDN2 || ''' , '''') = '''' THEN RIGHT ( TRIM ( A4791CARDN ) , 4 ) ELSE ''' || IN_CARDN2 || ''' END
		AND A4791AUTH = CASE WHEN IFNULL ( ''' || IN_AUTH || ''' , '''') = '''' THEN A4791AUTH ELSE ''' || IN_AUTH || ''' END
		AND A4791STATU = CASE WHEN IFNULL ( ''' || IN_STATUS || ''' , '''') = '''' THEN A4791STATU ELSE ''' || IN_STATUS || ''' END
		AND A4791TKT = CASE WHEN IFNULL ( ''' || IN_TICKET || ''' , '''') = '''' THEN A4791TKT ELSE ''' || IN_TICKET || ''' END
		AND A4791PROCE = CASE WHEN IFNULL ( ''' || IN_PROCINSUMO || ''' , '''') = '''' THEN A4791PROCE ELSE ''' || IN_PROCINSUMO || ''' END
		AND A4791PROSQ = CASE WHEN IFNULL ( ''' || IN_PROCMATCH || ''' , '''') = '''' THEN A4791PROSQ ELSE ''' || IN_PROCMATCH || ''' END

*/


