-- TABLA 
SELECT*FROM PRAXIS . A1819


-- revisar longitud de campos de la tabla
SELECT COLUMN_NAME, LENGTH
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'PRAXIS'
AND TABLE_NAME = 'A1819'
AND COLUMN_NAME IN ('A1819CECO','A1819CTA','A1819SCTA');



-- CAMBIAR LONGITUD DE CAMPOS DE TABLA
ALTER TABLE PRAXIS.A1819
ALTER COLUMN A1819CECO SET DATA TYPE VARCHAR(7);


ALTER TABLE PRAXIS.A1819
ALTER COLUMN A1819CTA SET DATA TYPE VARCHAR(6);