SELECT A.BANDOC,A.DATECI,A.TRANCI,A.SCOUNTRY,
(SELECT SUM(B.NETO) FROM PRAXISMP.MPF102 B 
WHERE B.BANDOC = A.BANDOC AND B.DATECI = A.DATECI AND B.TRANCI = A.TRANCI) NT,

(SELECT SUM(B.NETO) FROM PRAXISMP.MPF191 B 
WHERE B.BANDOC = A.BANDOC AND B.DATECI = A.DATECI AND B.TRANCI = A.TRANCI AND STVAL = '1') LQM,
(SELECT SUM(B.NETO) FROM PRAXISMP.MPF191 B 
WHERE B.BANDOC = A.BANDOC AND B.DATECI = A.DATECI AND B.TRANCI = A.TRANCI AND STVAL <> '1') LQP,
(SELECT SUM(B.PAYAMOU) FROM PRAXISMP.MPF199 B 
WHERE B.BANDOC = A.BANDOC AND B.DATECI = A.DATECI AND B.TRANCI = A.TRANCI) AD,
(
 SELECT SUM(CASE WHEN B.SPAYMENT = 'EP' THEN B.SVFOP ELSE B.SVFOPNETR END) FROM PRAXISMP.MPF300 B 
WHERE B.BANDOC = A.BANDOC AND B.DATECI = A.DATECI AND B.TRANCI = A.TRANCI
) VT
FROM PRAXISMP.MPF191 A
GROUP BY A.BANDOC,A.DATECI,A.TRANCI,A.SCOUNTRY


1700261870	20250902	000005462


CALL PRAXISMP.SPGCON018('1700261870','20250902','000005462','20251104','PRUEBA')
   SELECT * FROM PRAXISMP.A4545 WHERE A4545USER = 'PRUEBA'
  DELETE PRAXISMP.A4545 WHERE A4545USER = 'PRUEBA'
  
  
  
  