


/*CONSULTAS PARA LOS TAB DE LA VISTA */
SELECT * FROM PRAXIS.INF053 WHERE NPROG='PX00000034'   -- PERMISOS
SELECT * FROM PRAXIS.INF021 WHERE NPROG='PX00000676';   -- VISTA
SELECT * FROM PRAXIS.INF050 WHERE NPROG='PX00000676';




SELECT * FROM PRAXIS.A4622 WHERE STVAL='4' AND STUSE != 'USED'
SELECT * FROM PRAXIS.A4622 WHERE STVAL='4' AND STUSE = 'OK'



/*****************************************************************************/

SELECT * FROM PRAXIS.A4622

/*****************************************************************************/


/* permisos*/
GRANT ALL ON PROCEDURE PRAXISMP.SQP05716 TO PUBLIC  -- PARA TODOS PUEDAN USAR


/*****************************************************************************/

/*VARIABLES PARA PRRUEBA*/
CREATE OR REPLACE VARIABLE PRAXISMP.TES_STATUS INTEGER
CREATE OR REPLACE VARIABLE PRAXISMP.TES_MSG VARCHAR(300)
VALUES PRAXISMP.TES_MSG   -- PARA LA RESPUESTA


/*ELIMINAR VARIABLES*/
DROP VARIABLE PRAXISMP.TES_STATUS 
DROP VARIABLE PRAXISMP.TES_MSG

/*PRUEBA*/
CALL PRAXISMP.MPS245('C','','134','','1','pRUEBA','',PRAXISMP.TES_STATUS,PRAXISMP.TES_MSG)

SELECT * FROM PRAXIS.INF020

/*****************************************************************************/

/*BUSCAR ULTIMOS CREADOS*/
SELECT * FROM PRAXIS.INF021 WHERE NPROG LIKE '%PX00000%' ORDER BY NPROG DESC LIMIT 10;


/*CREAR NUEVO MENU*/
INSERT INTO PRAXIS.INF021(CCUST,APLICA,MODUL,MTYPE,MENU,SMENU,TRANSA,DESC1,DESC2,NPROG,ICONO,ICONO2,STAT,USRC,DATC,TIMC,CRTC,USRM,DATM,TIMM,CRTM)
VALUES ('139','PX','MAIN','1','21','210','0006','Tax Log Error','','PX00000691','','','A','SAP54T','20251103','153000','10.0.0.83','','','','');


/*CREAR SUB MENU*/
INSERT INTO PRAXIS.INF050(APLICA,NPROG,PROG,NAVTARG,DESC1,DESC2,STAT,USRC,DATC,TIMC,CRTC,USRM,DATM,TIMM,CRTM) 
VALUES ('PX','PX00000691','Tax Log Error','salesAudit-taxlogerror-form','','','A','SAP54T','20251103','153000','10.0.0.83','','','','');

/*DAR PERMISOS*/
INSERT INTO PRAXIS.INF053(CCUST,USR,APLICA,NPROG,PERMA,PERML,PERMC,PERMM,PERME,PERMX,STAT,USCR,DTCR)
VALUES('139','SAP54D','PX','PX00000117','Y','Y','Y','Y','Y','Y','A','SAP54D','2026-03-12 10:36:01')




--PX00000647


SELECT DISTINCT TPAX 
FROM PRAXIS.A4622
ORDER BY TPAX;


SELECT * FROM PRAXIS.A4622
				   --CCUST, FPROCF,    FPROCT,  STVAL,TPAX,FTE,TICKET
CALL PRAXIS.SQP05424('139','20231001','20251006','','','','')




SELECT SPECIFIC_SCHEMA,
       SPECIFIC_NAME,
       ORDINAL_POSITION,
       PARAMETER_MODE,
       PARAMETER_NAME,
       DATA_TYPE,
       CHARACTER_MAXIMUM_LENGTH
FROM QSYS2.SYSPARMS
WHERE SPECIFIC_SCHEMA = 'PRAXIS'
  AND SPECIFIC_NAME = 'SQP05424'
ORDER BY ORDINAL_POSITION;


--------------

SELECT 
    SPECIFIC_SCHEMA AS ESQUEMA,
    --SPECIFIC_NAME AS NOMBRE_ESPECIFICO,
    PARAMETER_NAME AS PARAMETROS,
    DATA_TYPE AS TIPO
FROM QSYS2.SYSPARMS
WHERE SPECIFIC_SCHEMA = 'PRAXIS'    
  AND SPECIFIC_NAME = 'SQP05424'
  
  
  
  
SELECT A4451DESC1 FROM PRAXISMP.A4451 WHERE A4451KEY1 = 'PR' AND A4451FECH1 = 'P' AND A4451STS = 1 AND A4451KEY2='AMEX01'




SELECT * FROM PRAXIS.A1830

