SELECT * FROM PRAXISJS.INF021 WHERE NPROG LIKE '%PX00000%' ORDER BY NPROG DESC LIMIT 10;


--permisos
SELECT * FROM PRAXISJS.INF053; 

--programa viewTicket
SELECT * FROM PRAXISJS.INF053 WHERE NPROG ='PX00000040';

-- cantidad de permisos
SELECT * FROM PRAXISJS.INF053 WHERE USCR ='SAJ45T';


INSERT INTO PRAXISJS.INF053(CCUST,USR,APLICA,NPROG,PERMA,PERML,PERMC,PERMM,PERME,PERMX,STAT,USCR,DTCR)
VALUES('973','SAJ45T','PX','PX00000040','Y','Y','Y','Y','Y','Y','A','SAJ45T','2026-03-24 10:36:01');
 



--de donde sacas esquema
SELECT 
    SPECIFIC_SCHEMA AS ESQUEMA,
    SPECIFIC_NAME AS NOMBRE_SP,
    PARAMETER_NAME AS PARAMETRO,
    DATA_TYPE AS TIPO
FROM QSYS2.SYSPARMS
WHERE SPECIFIC_NAME = 'PX095S01A1691';