



CREATE OR REPLACE PROCEDURE PRAXISMP.SQP05716 (
    IN IN_PRDAF VARCHAR(8),
    IN IN_PRDATO VARCHAR(8),
    IN IN_KEY1 VARCHAR(20),
    IN IN_KEY2 VARCHAR(20),
    IN IN_KEY3 VARCHAR(20),
    IN IN_KEY4 VARCHAR(20),
    INOUT IO_PAGNUM INTEGER,
    INOUT IO_PAGROW INTEGER,
    INOUT IO_TOTPAG INTEGER,
    INOUT IO_TOTROW INTEGER
)
RESULT SETS 1
LANGUAGE SQL
BEGIN
    DECLARE V_SQL VARCHAR(30000);
    DECLARE CURRES CURSOR FOR STMTRES;

    -- 
    SET V_SQL = 'SELECT A.*, CASE WHEN B.KEY1 IS NULL THEN ''NO EXISTE EN B'' ELSE ''EXISTE'' END AS ESTADO
                 FROM PRAXISMP.TABLA_A A
                 LEFT JOIN PRAXISMP.TABLA_B B
                   ON A.KEY1 = B.KEY1
                  AND A.KEY2 = B.KEY2
                  AND A.KEY3 = B.KEY3
                  AND A.KEY4 = B.KEY4
                 WHERE A.PERIODO BETWEEN ''' || IN_PRDAF || ''' AND ''' || IN_PRDATO || '''';

    -- 
    CALL PRAXISMP.PAGINATE(V_SQL, IO_PAGNUM, IO_PAGROW, IO_TOTPAG, IO_TOTROW);

    -- 
    PREPARE STMTRES FROM V_SQL;
    OPEN CURRES;
END
