SELECT * FROM PXSAUDIT.A4877 

CREATE OR REPLACE VARIABLE PXSAUDIT.IO_PAGNUM INTEGER DEFAULT 1
CREATE OR REPLACE VARIABLE PXSAUDIT.IO_PAGROW INTEGER DEFAULT 10
CREATE OR REPLACE VARIABLE PXSAUDIT.IO_TOTPAG INTEGER DEFAULT 0
CREATE OR REPLACE VARIABLE PXSAUDIT.IO_TOTROW INTEGER DEFAULT -1

DROP VARIABLE PXSAUDIT.IO_PAGNUM 
	DROP VARIABLE PXSAUDIT.IO_PAGROW 
	DROP VARIABLE PXSAUDIT.IO_TOTPAG 
	DROP VARIABLE PXSAUDIT.IO_TOTROW

CALL PXSAUDIT.SQP05832('1','139','','','BPBSJT',
	PXSAUDIT.IO_PAGNUM,
    PXSAUDIT.IO_PAGROW,
    PXSAUDIT.IO_TOTPAG,
    PXSAUDIT.IO_TOTROW
)




--PNR
BT9B4M




--TKT