SELECT*FROM PRAXIS . A1806


-- revisar longitud de campos de la tabla
SELECT COLUMN_NAME, LENGTH
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'PRAXIS'
AND TABLE_NAME = 'A1806'
AND COLUMN_NAME IN ('A1806CENCO','A1806CUENT','A1806SUBCT');



-- CAMBIAR LONGITUD DE CAMPOS DE TABLA
ALTER TABLE PRAXIS.A1806
ALTER COLUMN A1806CENCO SET DATA TYPE VARCHAR(7);


ALTER TABLE PRAXIS.A1806
ALTER COLUMN A1806CUENT SET DATA TYPE VARCHAR(6);