CREATE OR REPLACE PROCEDURE PRAXISMP.SQP05744 ( IN IN_CCUST VARCHAR(3),
                                     IN IN_DATEFROM VARCHAR(10),
                                     IN IN_DATETO VARCHAR(10),
                                     IN IN_USER VARCHAR(10),
                                     INOUT IO_PAGNUM INTEGER,
                                     INOUT IO_PAGROW INTEGER,
                                     INOUT IO_TOTPAG INTEGER,
                                     INOUT IO_TOTROW INTEGER )
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC PRAXISMP.SQP05744

BEGIN

DECLARE V_SQL VARCHAR ( 8000 ) ;
DECLARE V_SQLWREPAR VARCHAR ( 8000 ) DEFAULT '' ;

DECLARE SQLCNT01 VARCHAR ( 8000 ) ;
DECLARE PAGROWINIT INTEGER ;
DECLARE SQLPAG01 VARCHAR ( 8000 ) ;

DECLARE CURQRY01 CURSOR FOR STMTQRY01 ;



SET IN_DATEFROM = REPLACE ( IN_DATEFROM , '/' , '' ) ;
SET IN_DATETO = REPLACE ( IN_DATETO , '/' , '' ) ;
SET V_SQLWREPAR = ' AND FEAUT BETWEEN ''' CONCAT IN_DATEFROM CONCAT ''' AND ''' CONCAT IN_DATETO CONCAT ''' ' ;
--
IF LENGTH ( IN_USER ) > 0 THEN
	SET V_SQLWREPAR = V_SQLWREPAR CONCAT ' AND AUASI = ''' CONCAT IN_USER CONCAT ''' ' ;
END IF ;

--,''AUTOPR''	AND A3389REGAS NOT IN('''',''AUTOAM'')
--SET V_SQL = 'SELECT PRDA,SCOUNTRY,PROCTYPE,PROCTYPESQ,PMERCHID,SCARDN,SAUTHOC,SPNR,TICKET,QTYTKT,TDOC,SCURRENCY,TRANSTYPE,
			--		GRUPOT,NBRLIQUID,CODCHGBACK,FEAUT,HOAUT,AUASI,FEASI,HOASI,ROW_NUMBER() OVER(ORDER BY AUASI) AS RN
			-- FROM PRAXISMP.A4331
			-- WHERE CCUST = ''' CONCAT IN_CCUST CONCAT ''' ' CONCAT V_SQLWREPAR CONCAT ' ' ;
	SET V_SQL = '
	    SELECT 
	        A1.PRDA,
	        A1.SCOUNTRY,
	        A1.PROCTYPE,
	        A1.PROCTYPESQ,
	        A1.PMERCHID,
	        A1.SCARDN,
	        A1.SAUTHOC,
	        A1.SPNR,
	        A1.TICKET,
	        A1.QTYTKT,
	        A1.TDOC,
	        A1.SCURRENCY,
	        A1.TRANSTYPE,
	        A1.GRUPOT,
	        A1.NBRLIQUID,
	        A1.CODCHGBACK,
	        A1.FEAUT,
	        A1.HOAUT,
	        A1.AUASI,
	        A1.FEASI,
	        A1.HOASI,
	        ROW_NUMBER() OVER(ORDER BY A1.AUASI) AS RN,
	        A4.A4451DESC1 AS PROCTYPE_DESC
	    FROM PRAXISMP.A4331 A1
	    LEFT JOIN PRAXISMP.A4451 A4
	        ON A4.A4451KEY1 = ''PR''
	        AND A4.A4451FECH1 = ''P''
	        AND A4.A4451STS = 1
	        AND A4.A4451KEY2 = A1.PROCTYPESQ
	    WHERE A1.CCUST = ''' || IN_CCUST || ''' ' || V_SQLWREPAR || '
	';

			
			

IF IO_TOTROW = - 1 THEN
	SET SQLPAG01 = 'SELECT COUNT(*) FROM ( 	 ' CONCAT V_SQL CONCAT ' ) TB' ;

PREPARE STMTQRY01 FROM SQLPAG01 ;
OPEN CURQRY01 ;
FETCH_LOOP :
LOOP
FETCH CURQRY01 INTO IO_TOTROW ;
LEAVE FETCH_LOOP ;
END LOOP FETCH_LOOP ;
CLOSE CURQRY01 ;
END IF ;

SET IO_PAGNUM = PRAXIS . F0001 ( 'PAGNUM' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
SET IO_PAGROW = PRAXIS . F0001 ( 'PAGROW' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
SET IO_TOTPAG = PRAXIS . F0001 ( 'TOTPAG' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
SET IO_TOTROW = PRAXIS . F0001 ( 'TOTROW' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
SET PAGROWINIT = PRAXIS . F0001 ( 'PRINIT' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;

SET SQLPAG01 = 'SELECT * FROM (' CONCAT V_SQL CONCAT ') AS RS WHERE RS.RN > ' CONCAT PAGROWINIT CONCAT '  ' ;
IF IO_PAGROW > 0 THEN
SET SQLPAG01 = SQLPAG01 CONCAT ' FETCH FIRST ' CONCAT IO_PAGROW CONCAT ' ROWS ONLY' ;
END IF ;

PREPARE STMTQRY01 FROM SQLPAG01 ;
OPEN CURQRY01 ;

END





DROP PROCEDURE PRAXISMP.SQP05744