-- TABLA 
SELECT*FROM PRAXIS . A1835


-- revisar longitud de campos de la tabla
SELECT COLUMN_NAME, LENGTH
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'PRAXIS'
AND TABLE_NAME = 'A1835'
AND COLUMN_NAME IN ('A1835CENCO','A1835CUENT');



-- CAMBIAR LONGITUD DE CAMPOS DE TABLA
ALTER TABLE PRAXIS.A1835
ALTER COLUMN A1835CENCO SET DATA TYPE VARCHAR(7);


ALTER TABLE PRAXIS.A1835
ALTER COLUMN A1835CUENT SET DATA TYPE VARCHAR(6);