CREATE PROCEDURE PRAXISMP.SQP05060 ( IN IN_CCUST VARCHAR(3),
                                     IN IN_DATE VARCHAR(10),
                                     IN IN_MONTH VARCHAR(6),
                                     IN IN_DATEFROM VARCHAR(8),
                                     IN IN_DATETO VARCHAR(8),
                                     IN IN_PROCTYPE VARCHAR(10),
                                     IN IN_PROCTYPESQ VARCHAR(10),
                                     IN IN_SMERCHID VARCHAR(30),
                                     IN IN_TRANSTYPE VARCHAR(5),
                                     IN IN_SCOUNTRY VARCHAR(2),
                                     IN IN_FVOID VARCHAR(1),
                                     IN IN_TICKET VARCHAR(13),
                                     IN IN_SCARDN VARCHAR(30),
                                     IN IN_SAUTHOC VARCHAR(9),
                                     IN IN_SPNR VARCHAR(8),
                                     IN IN_TYPE VARCHAR(2),
                                     IN IN_STVAL VARCHAR(1),
                                     IN IN_CERROR VARCHAR(2),
                                     IN IN_CODADJU VARCHAR(2),
                                     IN IN_AREFNBR VARCHAR(30),
                                     IN IN_AMOUNT NUMERIC(16, 2),
                                     IN IN_SCURRENCY VARCHAR(3),
                                     IN IN_NBRINSTA VARCHAR(1),
                                     IN IN_CODEAUTOCOMMENT VARCHAR(2),
                                     IN IN_FREGLA VARCHAR(1),
                                     INOUT IO_PAGNUM INTEGER,
                                     INOUT IO_PAGROW INTEGER,
                                     INOUT IO_TOTPAG INTEGER,
                                     INOUT IO_TOTROW INTEGER )
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC PRAXISMP.SQP05060

BEGIN

	-- SQP GET DETAIL BY PAYMENT

	DECLARE V_SQL VARCHAR ( 10000 ) ;
	DECLARE V_WHERE VARCHAR ( 5000 ) DEFAULT '' ;
	DECLARE V_PROCTYPE VARCHAR ( 15 ) ;
	DECLARE V_STS_MATCH VARCHAR ( 1000 ) ;

	--DATOS PARA BUSCAR EN DESGLOSE
	DECLARE V_CCIA VARCHAR ( 3 ) ;
	DECLARE V_FORMA VARCHAR ( 4 ) ;
	DECLARE V_SERIE VARCHAR ( 6 ) ;

	--paginado
	DECLARE PAGROWINIT INTEGER ;
	DECLARE SQLCNT01 VARCHAR ( 5000 ) ;
	DECLARE SQLPAG01 VARCHAR ( 5000 ) ;
	DECLARE CURQRY01 CURSOR FOR STMTQRY01 ;
	DECLARE CURCNT01 CURSOR FOR STMTCNT01 ;

	SET V_SQL = '
		SELECT ROW_NUMBER() OVER (ORDER BY A.{DATE},A.AREFNBR) as RN,A.*
		, CASE WHEN TRIM ( TRANSTYPE ) = ''CHBK'' THEN A.TGROSAMOUN + A.SVFOPS ELSE ABS(A.TGROSAMOUN) - ABS(A.SVFOPS) END AS DIFFERENCE,
		(SELECT K.A4451DESC1 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 = ''PR'' AND K.A4451KEY2 = A.PROCTYPESQ AND K.A4451KEY3 = A.PROCTYPE) DESC_PROCTYPE,
		IFNULL((SELECT A4451DESC1 FROM PRAXISMP.A4451 WHERE A4451KEY1= ''PK'' AND A4451KEY2=''86'' AND A4451KEY3= A.CERROR),'''') DES_CERROR,
		IFNULL((SELECT A4451DESC1 FROM PRAXISMP.A4451 WHERE A4451KEY1= ''PK'' AND A4451KEY2=''89'' AND A4451KEY3= A.CODADJU),'''') DESC_CODADJU,
	    IFNULL( ( PM.DESCR ) , '''') AS DES_MERCHANT,
		IFNULL( ( SM.DESCR ) , '''') AS DES_SMERCHANT,
		IFNULL((SELECT TRIM(OBSERV) FROM PRAXISMP.A4495 WHERE CCUST = A.CCUST AND PRDA = A.PRDA AND TDOC = A.TDOC AND AREFNBR = A.AREFNBR AND TYPE=''SB'' ),'''') AS BPOCOMENT,
		IFNULL((SELECT TRIM(OBSERV) FROM PRAXISMP.A4495 WHERE CCUST = A.CCUST AND PRDA = A.PRDA AND TDOC = A.TDOC AND AREFNBR = A.AREFNBR AND TYPE=''89'' ),'''') AS ADJUCOMENT,
	    PRAXISMP.FN_IATA_SETTLEMENT ( A.CCUST , A.TDOC , A.PRDA , A.AREFNBR , A.STVAL ) AS IATA
		FROM PRAXISMP.A4331 A
			LEFT JOIN PRAXISMP.A2354 PM ON A.PMERCHID = PM.MERCHN
	        LEFT JOIN PRAXISMP.A2354 SM ON A.SMERCHID = SM.MERCHN
		WHERE A.CCUST = {CCUST} AND A.{DATE} BETWEEN ''{FROM}'' AND ''{TO}''
		{WHERE}
		ORDER BY A.{DATE},A.AREFNBR ' ;

	CASE IN_DATE
		WHEN 'PAYDATE' THEN
			SET V_SQL = REPLACE ( V_SQL , '{DATE}' , 'PAYDATE' ) ;
		WHEN 'PRDA' THEN
			SET V_SQL = REPLACE ( V_SQL , '{DATE}' , 'PRDA' ) ;
		WHEN 'FEUP' THEN
			SET V_SQL = REPLACE ( V_SQL , '{DATE}' , 'FEUP' ) ;
	END CASE ;
/*
	IF IN_DATE = 'PAYDATE' THEN
		SET V_SQL = REPLACE ( V_SQL , '{DATE}' , 'PAYDATE' ) ;
	ELSE
		SET V_SQL = REPLACE ( V_SQL , '{DATE}' , 'PRDA' ) ;
	END IF ;
*/
	SET V_SQL = REPLACE ( V_SQL , '{CCUST}' , IN_CCUST ) ;

	IF IN_MONTH <> '' THEN
		SET V_SQL = REPLACE ( V_SQL , '{FROM}' , IN_MONTH || '01' ) ;
		SET V_SQL = REPLACE ( V_SQL , '{TO}' , IN_MONTH || '31' ) ;
	ELSE
		SET V_SQL = REPLACE ( V_SQL , '{FROM}' , IN_DATEFROM ) ;
		SET V_SQL = REPLACE ( V_SQL , '{TO}' , IN_DATETO ) ;
	END IF ;

	IF IN_PROCTYPE <> '' THEN
		SET V_WHERE = V_WHERE || ' AND PROCTYPE = ''' || IN_PROCTYPE || '''' ;
	END IF ;

	IF IN_PROCTYPESQ <> '' THEN
		IF TRIM ( IN_PROCTYPE ) = '' THEN
			SELECT A4451KEY3 INTO V_PROCTYPE FROM PRAXISMP . A4451 WHERE A4451KEY1 = 'PR' AND A4451KEY2 = IN_PROCTYPESQ ;
			SET V_WHERE = V_WHERE || ' AND PROCTYPE = ''' || V_PROCTYPE || '''' ;
		END IF ;
		SET V_WHERE = V_WHERE || ' AND PROCTYPESQ = ''' || IN_PROCTYPESQ || '''' ;
	END IF ;

	IF IN_TRANSTYPE <> '' THEN
		IF IN_TRANSTYPE = 'RCHBK' THEN
			--FILTRO DE REVERSA CHARGEBACK
			SET IN_TRANSTYPE = 'CHBK' ;
			SET V_WHERE = V_WHERE || ' AND TGROSAMOUN > 0' ;
		ELSEIF IN_TRANSTYPE = 'NCHBK' THEN
			--FILTRO DE CHARGEBACK (NEGATIVOS)
			SET IN_TRANSTYPE = 'CHBK' ;
			SET V_WHERE = V_WHERE || ' AND TGROSAMOUN <= 0' ;
		ELSEIF IN_TRANSTYPE = 'CHBK' THEN
			SET IN_TRANSTYPE = 'CHBK' ;
		END IF ;
		SET V_WHERE = V_WHERE || ' AND TRANSTYPE = ''' || IN_TRANSTYPE || '''' ;
	END IF ;

	IF IN_SMERCHID <> '' THEN
		SET V_WHERE = V_WHERE || ' AND SMERCHID = ''' || IN_SMERCHID || '''' ;
	END IF ;

	IF IN_SCOUNTRY <> '' THEN
		SET V_WHERE = V_WHERE || ' AND SCOUNTRY = ''' || IN_SCOUNTRY || '''' ;
	END IF ;

	IF IN_SCURRENCY <> '' THEN
		SET V_WHERE = V_WHERE || ' AND SCURRENCY = ''' || IN_SCURRENCY || '''' ;
	END IF ;

	IF IN_FVOID <> '' THEN
		SET V_WHERE = V_WHERE || ' AND FVOID = ''V''' ;
	END IF ;

	IF IN_TICKET <> '' THEN
		IF LENGTH ( IN_TICKET ) = 13 THEN
			--DESGLOSE BOLETO
			SET V_CCIA = LEFT ( IN_TICKET , 3 ) ;
			SET V_FORMA = SUBSTRING ( IN_TICKET , 4 , 4 ) ;
			SET V_SERIE = RIGHT ( IN_TICKET , 6 ) ;
			--BUSQUEDA EN DESGLOSE LIQUIDACION Y CHBK
			SET V_WHERE = V_WHERE || ' AND AREFNBR IN (
			SELECT DISTINCT D.AREFNBR AREFNBR FROM PRAXISMP.A4335 D
				WHERE D.CCUST = ''' || IN_CCUST || '''
				AND D.CCIA = ''' || V_CCIA || '''
				AND D.FORMA = ''' || V_FORMA || '''
				AND D.SERIE = ''' || V_SERIE || '''
			UNION ALL
			SELECT DISTINCT CH.AREFNBR AREFNBR FROM PRAXISMP.A4482 CH
				WHERE CH.CCUST = ''' || IN_CCUST || '''
				AND CH.CCIA = ''' || V_CCIA || '''
				AND CH.FORMA = ''' || V_FORMA || '''
				AND CH.SERIE = ''' || V_SERIE || '''
			) ' ;
		END IF ;
	END IF ;

	IF IN_SCARDN <> '' THEN
		SET V_WHERE = V_WHERE || ' AND SCARDN LIKE ''' || IN_SCARDN || '''' ;
	END IF ;

	IF IN_SAUTHOC <> '' THEN
		SET V_WHERE = V_WHERE || ' AND SAUTHOC = ''' || IN_SAUTHOC || '''' ;
	END IF ;

	IF IN_SPNR <> '' THEN
		SET V_WHERE = V_WHERE || ' AND SPNR = ''' || IN_SPNR || '''' ;
	END IF ;

	IF IN_STVAL <> '' THEN
		SET V_WHERE = V_WHERE || ' AND STVAL = ''' || IN_STVAL || '''' ;
	END IF ;

	IF IN_CERROR <> '' THEN
		SET V_WHERE = V_WHERE || ' AND CERROR = ''' || IN_CERROR || '''' ;
	END IF ;

	IF IN_CODADJU <> '' THEN
		SET V_WHERE = V_WHERE || ' AND CODADJU = ''' || IN_CODADJU || '''' ;
	END IF ;

	IF IN_AREFNBR <> '' THEN
		SET V_WHERE = V_WHERE || ' AND AREFNBR = ''' || IN_AREFNBR || '''' ;
	END IF ;

	IF IN_NBRINSTA <> '' THEN
		SET V_WHERE = V_WHERE || ' AND NBRINSTA > ' || IN_NBRINSTA || ' ' ;
	END IF ;

	IF IN_AMOUNT IS NOT NULL THEN
		SET V_WHERE = V_WHERE || ' AND TGROSAMOUN = ' || IN_AMOUNT || ' ' ;
	END IF ;

	IF IN_FREGLA <> '' THEN
		SET V_WHERE = V_WHERE || ' AND FREGLA = ''' || IN_FREGLA || '''' ;
	END IF ;


	-- 05/08/2025 AGREGAR FILTRO DE COMENTARIO
	IF IN_CODEAUTOCOMMENT <> '' THEN
		SET V_WHERE = V_WHERE || ' AND EXISTS ( SELECT * FROM PRAXISMP.A4495 C WHERE C.CCUST = A.CCUST AND C.PRDA = A.PRDA AND C.TDOC = A.TDOC AND C.AREFNBR = A.AREFNBR AND C.PROCTYPE = A.PROCTYPE AND C.PROCTYPESQ = A.PROCTYPESQ AND C.TYPE = ''90'' AND C.CODE = ''' || IN_CODEAUTOCOMMENT || ''' ) ' ;
	END IF ;
	--TIPO DE BUSQUEDA
	/*IF IN_TYPE = 'M' THEN
		SET V_WHERE = V_WHERE|| ' AND STVAL IN (''1'',''5'',''6'',''7'')';
	ELSEIF IN_TYPE = 'P' THEN
		SET V_WHERE = V_WHERE|| ' AND STVAL NOT IN (''1'',''5'',''6'',''7'')';
	END IF;*/


	IF IN_TYPE <> '' AND IN_TYPE <> 'T' THEN

		--DP: 16/06/2025 - CAMBIO PARA MOSTRAR SOLO MATCH O SOLO PENDIENTES
		SELECT LISTAGG ( '''' || TRIM ( TM . A4451KEY3 ) || '''' , ',' ) INTO V_STS_MATCH
			FROM PRAXISMP . A4451 TM WHERE TM . A4451KEY1 = 'PK' AND TM . A4451KEY2 = 'STVAL' AND A4451CANT1 = 1 ; -- A4451CANT1 : (1 es match, 0 son pending)

		CASE IN_TYPE
			WHEN 'M' THEN
-- 				SET V_WHERE = V_WHERE || ' AND STVAL IN (''1'',''5'',''6'',''7'')' ;
				SET V_WHERE = V_WHERE || ' AND STVAL IN (' || V_STS_MATCH || ') ' ;
			WHEN 'P' THEN
-- 				SET V_WHERE = V_WHERE || ' AND STVAL NOT IN (''1'',''5'',''6'',''7'')' ;
				SET V_WHERE = V_WHERE || ' AND STVAL NOT IN (' || V_STS_MATCH || ') ' ;
			WHEN 'XM' THEN
-- 				SET V_WHERE = V_WHERE || ' AND STVAL IN (''1'',''5'',''6'',''7'') AND SMERCHID NOT IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'')' ;
				SET V_WHERE = V_WHERE || ' AND STVAL IN (' || V_STS_MATCH || ') AND SMERCHID NOT IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'')' ;
			WHEN 'XP' THEN
-- 				SET V_WHERE = V_WHERE || ' AND STVAL NOT IN (''1'',''5'',''6'',''7'') AND SMERCHID NOT IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'')' ;
				SET V_WHERE = V_WHERE || ' AND STVAL NOT IN (' || V_STS_MATCH || ') AND SMERCHID NOT IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'')' ;
			WHEN 'PM' THEN
-- 				SET V_WHERE = V_WHERE || ' AND STVAL IN (''1'',''5'',''6'',''7'') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHPLUS'')' ;
				SET V_WHERE = V_WHERE || ' AND STVAL IN (' || V_STS_MATCH || ') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHPLUS'')' ;
			WHEN 'PP' THEN
-- 				SET V_WHERE = V_WHERE || ' AND STVAL NOT IN (''1'',''5'',''6'',''7'') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHPLUS'')' ;
				SET V_WHERE = V_WHERE || ' AND STVAL NOT IN (' || V_STS_MATCH || ') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHPLUS'')' ;
			WHEN 'LM' THEN
-- 				SET V_WHERE = V_WHERE || ' AND STVAL IN (''1'',''5'',''6'',''7'') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHLIG'')' ;
				SET V_WHERE = V_WHERE || ' AND STVAL IN (' || V_STS_MATCH || ') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHLIG'')' ;
			WHEN 'LP' THEN
-- 				SET V_WHERE = V_WHERE || ' AND STVAL NOT IN (''1'',''5'',''6'',''7'') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHLIG'')' ;
				SET V_WHERE = V_WHERE || ' AND STVAL NOT IN (' || V_STS_MATCH || ') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHLIG'')' ;
			WHEN 'TM' THEN
-- 				SET V_WHERE = V_WHERE || ' AND STVAL IN (''1'',''5'',''6'',''7'') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHTAB'')' ;
				SET V_WHERE = V_WHERE || ' AND STVAL IN (' || V_STS_MATCH || ') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHTAB'')' ;
			WHEN 'TP' THEN
-- 				SET V_WHERE = V_WHERE || ' AND STVAL NOT IN (''1'',''5'',''6'',''7'') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHTAB'')' ;
				SET V_WHERE = V_WHERE || ' AND STVAL NOT IN (' || V_STS_MATCH || ') AND SMERCHID IN (SELECT K.A4451KEY3 FROM PRAXISMP.A4451 K WHERE K.A4451KEY1 =''AC'' AND K.A4451KEY2 =''MERCHTAB'')' ;
		END CASE ;
	END IF ;
		
	


	SET V_SQL = REPLACE ( V_SQL , '{WHERE}' , V_WHERE ) ;

	--TRUNCATE TABLE PRAXISMP.X3170;
	--INSERT INTO PRAXISMP.X3170 VALUES('SQP05060',V_SQL);

	/*
	 * Paginado
	 */

	IF IO_TOTROW = - 1 THEN
		SET SQLCNT01 = ' SELECT COUNT (*) AS F_TOTROW FROM ( ' || V_SQL ;

		SET SQLCNT01 = SQLCNT01 CONCAT ' ) AS TBCOUNT' ;

		PREPARE STMTCNT01 FROM SQLCNT01 ;
		OPEN CURCNT01 ;
		FETCH_LOOP :
			LOOP
			FETCH CURCNT01 INTO IO_TOTROW ;
			LEAVE FETCH_LOOP ;
			END LOOP FETCH_LOOP ;
			CLOSE CURCNT01 ;
	END IF ;

	SET IO_PAGNUM = PRAXIS . F0001 ( 'PAGNUM' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_PAGROW = PRAXIS . F0001 ( 'PAGROW' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_TOTPAG = PRAXIS . F0001 ( 'TOTPAG' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_TOTROW = PRAXIS . F0001 ( 'TOTROW' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET PAGROWINIT = PRAXIS . F0001 ( 'PRINIT' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;

	SET SQLPAG01 = 'SELECT * FROM ( ' CONCAT V_SQL CONCAT ' ) AS
	RS WHERE RS.RN >  ' CONCAT PAGROWINIT ;
	IF IO_PAGROW > 0 THEN
		SET SQLPAG01 = SQLPAG01 CONCAT ' FETCH FIRST ' CONCAT IO_PAGROW CONCAT ' ROWS ONLY' ;
	END IF ;


	PREPARE STMTQRY01 FROM SQLPAG01 ;
	OPEN CURQRY01 ;
END






SELECT * FROM  PRAXISMP.A4331


GRANT ALL ON PROCEDURE PRAXISMP.SQP05716 TO PUBLIC  
