CREATE PROCEDURE PRAXIS.PX022S04PXA006 ( IN IN_CHOPTION CHAR(1),
                                         IN IN_CAMPO VARCHAR(8),
                                         IN IN_A006KEY VARCHAR(3),
                                         IN IN_A006KEY1 VARCHAR(40),
                                         IN IN_A006CURNUM VARCHAR(3),
                                         IN IN_A006CURALPHA VARCHAR(3),
                                         IN IN_A006CURNAME VARCHAR(21),
                                         IN IN_VUSUR VARCHAR(10),
                                         IN IN_VFEC VARCHAR(8),
                                         IN IN_VHOUR VARCHAR(8) )
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC PRAXIS.PX022S04PXA006

BEGIN

DECLARE IN_A006MONEDA VARCHAR ( 25 ) DEFAULT '' ;
	DECLARE VL_SQLCODE INT DEFAULT 0 ;
	DECLARE SQLCODE INTEGER DEFAULT 0 ;
	DECLARE VL_MESSAGE VARCHAR ( 100 ) DEFAULT NULL ;
	DECLARE SENDDATA CHAR ( 104 ) ;
	
	DECLARE CURQRY CURSOR FOR SELECT VL_MESSAGE AS VMESSAGE , VL_SQLCODE AS VSQLCODE FROM ( VALUES ( '' , 0 ) ) AS TBL ;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	SET VL_SQLCODE = REPLACE ( SQLCODE , '-' , '' ) ;

IF IN_CAMPO = 'COUNTRYS' THEN
SET IN_A006MONEDA = IN_A006CURNUM CONCAT ' ' CONCAT IN_A006CURALPHA CONCAT ' ' CONCAT SUBSTRING ( IN_A006CURNAME , 1 , 17 ) ;
ELSE
IF IN_CAMPO = 'CURRENCY' THEN
SET IN_A006MONEDA = IN_A006CURNUM CONCAT ' ' CONCAT IN_A006CURNAME ;
ELSE
SET IN_A006MONEDA = IN_A006CURNUM CONCAT ' ' CONCAT IN_A006CURALPHA CONCAT ' ' CONCAT SUBSTRING ( IN_A006CURNAME , 1 , 17 ) ;
END IF ;
END IF ;

IF IN_CHOPTION = 'I' THEN

	IF EXISTS ( SELECT A006KEY FROM LIBMIATEC . A006 WHERE A006KEY = IN_A006KEY ) THEN
			SET VL_MESSAGE = 'DUPLICATE KEY, VERIFY!' ;
			OPEN CURQRY ;
			RETURN ;
		ELSE
			INSERT INTO LIBMIATEC . A006 ( A006KEY , A006KEY1 , A006MONEDA )
			VALUES ( IN_A006KEY , IN_A006KEY1 , IN_A006MONEDA ) ;			
			SET SENDDATA = 'ADDA006      ' CONCAT LEFT ( IN_A006KEY CONCAT CHAR ( REPEAT ( ' ' , 30 ) , 30 ) , 30 ) ;	
	END IF ;
	

ELSEIF IN_CHOPTION = 'U' THEN

	UPDATE LIBMIATEC . A006
	SET A006KEY1 = IN_A006KEY1 , A006MONEDA = IN_A006MONEDA
	WHERE A006KEY = IN_A006KEY ;	
	SET SENDDATA = 'MODA006      ' CONCAT LEFT ( IN_A006KEY CONCAT CHAR ( REPEAT ( ' ' , 30 ) , 30 ) , 30 ) ;
		
ELSEIF IN_CHOPTION = 'D' THEN
	
	DELETE FROM LIBMIATEC . A006 WHERE A006KEY = IN_A006KEY ;
	SET SENDDATA = 'DELA006      ' CONCAT LEFT ( IN_A006KEY CONCAT CHAR ( REPEAT ( ' ' , 30 ) , 30 ) , 30 ) ;

END IF ;


IF ( VL_SQLCODE = 0 ) THEN
	CALL PRAXIS . SPCL3050 ( '139' ) ;
	CALL PRAXIS . SPRUT1147 ( SENDDATA ) ;
END IF ;



IF ( VL_SQLCODE <> 0 ) THEN		
	SELECT DB_MESSAGE INTO VL_MESSAGE FROM PRAXIS . INF054 WHERE DB_SQLCODE = VL_SQLCODE ;
	IF VL_MESSAGE IS NULL THEN
		SET VL_MESSAGE = 'AN UNEXPECTED ERROR OCCURRED, CODE ' CONCAT VL_SQLCODE ;
	END IF ;
ELSE
	SET VL_MESSAGE = 'Operation was successful' ;			
END IF ;

OPEN CURQRY ;
END