--<ScriptOptions statementTerminator=";"/>

CREATE PROCEDURE PRAXISMP.SPACR014 ( IN IN_CCUST CHAR(3),
                                     IN IN_VALDATEF CHAR(8),
                                     IN IN_VALDATET CHAR(8),
                                     IN IN_CODPRO VARCHAR(3),
                                     IN IN_BANDOC VARCHAR(10),
                                     IN IN_REFER VARCHAR(30),
                                     IN IN_STVAL CHAR(1),
                                     IN IN_TIPOCON CHAR(3),
                                     IN IN_IDCONT VARCHAR(25),
                                     IN IN_HEADER VARCHAR(20),
                                     INOUT IO_PAGNUM INTEGER,
                                     INOUT IO_PAGROW INTEGER,
                                     INOUT IO_TOTPAG INTEGER,
                                     INOUT IO_TOTROW INTEGER )
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC PRAXISMP.SPACR014

BEGIN
	
	DECLARE V_SQL VARCHAR ( 10000 ) ;
	DECLARE V_WHERE VARCHAR ( 5000 ) DEFAULT '' ;
	DECLARE V_WHERE_TF VARCHAR ( 3000 ) DEFAULT '' ;
	DECLARE V_WHERE_TBL VARCHAR ( 3000 ) DEFAULT '' ;
	DECLARE V_STS VARCHAR ( 300 ) DEFAULT '' ;
	DECLARE V_CCUST VARCHAR ( 300 ) ;
	
	--paginado
	DECLARE PAGROWINIT INTEGER ;
	DECLARE SQLCNT01 VARCHAR ( 5000 ) ;
	DECLARE SQLPAG01 VARCHAR ( 5000 ) ;
	DECLARE CURQRY01 CURSOR FOR STMTQRY01 ;
	DECLARE CURCNT01 CURSOR FOR STMTCNT01 ;
	
	/*
	SET V_SQL = 'SELECT ROW_NUMBER() OVER (ORDER BY A.CCUST,A.BANDOC,A.VALDATE) as RN,A.*,B.FECSAP,IFNULL(B.STSAP,''N'') STSAP,
				IFNULL(B.IDCONT,'''') IDACC,B.FCONT FECACC,B.TIPOCON,IFNULL(B.STCON,'''') STACC,B.HEADER,B.FILENAM,
				IFNULL((SELECT TRIM(A4451DESC2) FROM PRAXISMP.A4451 
				WHERE A4451CCUST = ''134'' AND A4451KEY1 = ''PR'' AND A4451CORRL = 
					(CASE WHEN A.STVAL IN (''1'',''5'') AND A.CODPRO = '''' THEN ''CO'' ELSE A.CODPRO END) LIMIT 1),'''') DESC_PRO,
				(SELECT COUNT(0) FROM PRAXISMP.MPF060 L WHERE L.BANDOC = A.BANDOC AND L.DATECI = A.DATECI AND L.TRANCI = A.TRANCI) QTYLIQ1,
				(SELECT COUNT(0) FROM PRAXISMP.MPF101 L WHERE L.BANDOC = A.BANDOC AND L.DATECI = A.DATECI AND L.TRANCI = A.TRANCI) QTYLIQ2,
				(SELECT COUNT(0) FROM PRAXISMP.MPF091 G WHERE G.BANDOC = A.BANDOC AND G.DATECI = A.DATECI AND G.TRANCI = A.TRANCI) QTYGAS,
				(SELECT COUNT(DISTINCT R.IDCONT) FROM PRAXISMP.MPF137 R WHERE R.BANDOC = A.BANDOC AND R.DATECI = A.DATECI AND R.TRANCI = A.TRANCI) QTYREJ
				FROM PRAXISMP.MPF102 A
				LEFT JOIN PRAXISMP.MPF140 B
				ON A.BANDOC = B.BANDOC AND A.DATECI = B.DATECI AND A.TRANCI = B.TRANCI
				WHERE {CCUST} AND A.VALDATE BETWEEN ''{FROM}'' AND ''{TO}''
				{WHERE}
	';*/
	
	--SELECT * FROM PRAXISMP.MPF140
	SET V_SQL = 'SELECT ROW_NUMBER() OVER (ORDER BY TBL.CCUST,TBL.VALDATE,TBL.BANDOC) as RN,TBL.*,
				(SELECT COUNT(0) FROM PRAXISMP.MPF060 L WHERE L.BANDOC = TBL.BANDOC AND L.DATECI = TBL.DATECI AND L.TRANCI = TBL.TRANCI) QTYLIQ1,
				(SELECT COUNT(0) FROM PRAXISMP.MPF101 L WHERE L.BANDOC = TBL.BANDOC AND L.DATECI = TBL.DATECI AND L.TRANCI = TBL.TRANCI) QTYLIQ2,
				(SELECT COUNT(0) FROM PRAXISMP.MPF091 G WHERE G.BANDOC = TBL.BANDOC AND G.DATECI = TBL.DATECI AND G.TRANCI = TBL.TRANCI) QTYGAS,
				(SELECT COUNT(DISTINCT R.IDCONT) FROM PRAXISMP.MPF137 R WHERE R.BANDOC = TBL.BANDOC AND R.DATECI = TBL.DATECI AND R.TRANCI = TBL.TRANCI) QTYREJ
				FROM (
				SELECT A.CCUST,A.TDOC,A.BANDOC,A.VALDATE,A.ADATE,A.TEXTO,A.DATECI,A.TRANCI,A.ACCOUNT,A.BENCENC,A.CLAVE1,A.CLAVE3,A.SCURRENCY,A.NETO,A.STVAL,
				A.IDCONT,A.IDCDEB,LEFT(A.FCONT,6) PERIOD_REG, LEFT(A.FDEBIT,6) PERIOD_DEB, A.LOCRENCY2,A.LOCAMOUNT2,A.REFER,A.SOCIETY,
				IFNULL((SELECT TRIM(A4451DESC2) FROM PRAXISMP.A4451 
				WHERE A4451CCUST = ''134'' AND A4451KEY1 = ''PR'' AND A4451CORRL = 
					(CASE WHEN A.STVAL IN (''1'',''5'') AND A.CODPRO = '''' THEN ''CO'' ELSE A.CODPRO END) LIMIT 1),'''') DESC_PRO,
				B.HEADER,B.FILENAM,B.STCON TIPOREG,B.TIPOCON,B.STSAP,B.FECSAP,
				C.HEADER HEADER2,C.FILENAM FILENAM2,C.STCON TIPOREG2,C.TIPOCON TIPOCON2,C.STSAP STSAP2,C.FECSAP FECSAP2,
				A.ACCPROV,A.FECPROV
				FROM PRAXISMP.MPF102 A
				LEFT JOIN PRAXISMP.MPF140 B
				ON A.BANDOC = B.BANDOC AND A.DATECI = B.DATECI AND A.TRANCI = B.TRANCI AND B.STCON IN (''P'',''A'',''C'',''E'',''G'',''T'')
				LEFT JOIN PRAXISMP.MPF140 C
				ON A.BANDOC = C.BANDOC AND A.DATECI = C.DATECI AND A.TRANCI = C.TRANCI AND C.STCON IN (''D'',''B'')
				WHERE {CCUST} AND A.VALDATE BETWEEN ''{FROM}'' AND ''{TO}'' AND LEFT(A.BANDOC,2) <> ''CM'' 
				{WHERE}
				UNION ALL
				SELECT A.CCUST,(CASE WHEN A.CTIPO = ''D'' THEN ''S'' ELSE ''D'' END) TDOC,''CM''|| LPAD(A.CID,8,''0'') BANDOC,A.FVALOR VALDATE, A.FINGRESO ADATE,A.DESCRIPC TEXTO,A.FVALOR DATECI, A.FINGRESO TRANCI,
				'''' ACCOUNT,'''' BENCENC,'''' CLAVE1,'''' CLAVE3,A.MONEDA SCURRENCY,A.VCREDITO NETO,(CASE WHEN A.FSELECT = ''L'' THEN ''1'' ELSE ''3'' END) STVAL,
				B.IDCONT,C.IDCONT IDCDEB,LEFT(B.FCONT,6) PERIOD_REG, LEFT(C.FCONT,6) PERIOD_DEB, '''' LOCRENCY2,0 LOCAMOUNT2,(''CM''|| LPAD(A.CID,8,''0'')) REFER,''TA01'' SOCIETY,
				''CM TACAFLOW'' DESC_PRO,
				B.HEADER,B.FILENAM,B.STCON TIPOREG,B.TIPOCON,B.STSAP,B.FECSAP,
				C.HEADER HEADER2,C.FILENAM FILENAM2,C.STCON TIPOREG2,C.TIPOCON TIPOCON2,C.STSAP STSAP2,C.FECSAP FECSAP2,
				'''' ACCPROV,'''' FECPROV
				FROM PRAXISMP.MPF081 A 
				LEFT JOIN PRAXISMP.MPF140 B
				ON ''CM''|| LPAD(A.CID,8,''0'') = B.BANDOC AND A.FINGRESO = B.DATECI AND A.FVALOR = B.TRANCI AND B.STCON IN (''P'',''A'',''C'',''E'',''G'',''T'')
				LEFT JOIN PRAXISMP.MPF140 C
				ON ''CM''|| LPAD(A.CID,8,''0'') = C.BANDOC AND A.FINGRESO = C.DATECI AND A.FVALOR = B.TRANCI AND C.STCON IN (''D'',''B'')
				WHERE {CCUST} AND A.FVALOR BETWEEN ''{FROM}'' AND ''{TO}''
				{WHERE_TF}
				) AS TBL WHERE TBL.CCUST = TBL.CCUST
				{WHERE_TBL}
	' ;
	
	IF IN_CCUST = '' THEN
		SET V_CCUST = 'A.CCUST IN (''134'',''202'',''133'',''547'')' ;
	ELSE
		SET V_CCUST = 'A.CCUST = ''' || IN_CCUST || '''' ;
	END IF ;
	
	SET V_SQL = REPLACE ( V_SQL , '{CCUST}' , V_CCUST ) ;
	SET V_SQL = REPLACE ( V_SQL , '{FROM}' , IN_VALDATEF ) ;
	SET V_SQL = REPLACE ( V_SQL , '{TO}' , IN_VALDATET ) ;
	
	IF IN_CODPRO <> '' THEN
		SET V_WHERE = V_WHERE || ' AND (CASE 
				WHEN A.STVAL IN (''1'',''5'') THEN (CASE WHEN A.CODPRO = '''' THEN ''CO'' ELSE A.CODPRO END) 
				WHEN A.STVAL NOT IN (''1'',''5'') AND A.SCURRENCY = ''COP'' AND A.SCOUNTRY = ''CO'' AND A.CCUST = ''134'' THEN ''CO'' 
				ELSE IFNULL( (SELECT TRIM(A4451KEY2) FROM PRAXISMP.A4451 WHERE A4451CCUST = ''134''  
								AND A4451KEY1=''PR'' AND TRIM(A4451TTABL) = A.COREP LIMIT 1) ,''EXT'') END) = ''' || IN_CODPRO || '''' ;
		SET V_WHERE_TF = V_WHERE_TF || ' AND A.CODPRO = ''' || IN_CODPRO || '''' ;
	END IF ;
	
	IF IN_BANDOC <> '' THEN
		SET V_WHERE = V_WHERE || ' AND A.BANDOC = ''' || IN_BANDOC || '''' ;
		IF LEFT ( IN_BANDOC , 2 ) = 'CM' THEN
			SET V_WHERE_TF = V_WHERE_TF || ' AND A.CID = ' || CAST ( REPLACE ( IN_BANDOC , 'CM' , '' ) AS INT ) || '' ;
		ELSE
			SET V_WHERE_TF = V_WHERE_TF || ' AND A.CID = ' || 0 || '' ;
		END IF ;
	END IF ;
	
	IF IN_REFER <> '' THEN
		SET V_WHERE = V_WHERE || ' AND A.REFER = ''' || IN_REFER || '''' ;
		IF LEFT ( IN_REFER , 2 ) = 'CM' THEN
			SET V_WHERE_TF = V_WHERE_TF || ' AND A.CID = ' || CAST ( REPLACE ( IN_REFER , 'CM' , '' ) AS INT ) || '' ;
		ELSE
			SET V_WHERE_TF = V_WHERE_TF || ' AND A.CID = ' || 0 || '' ;
		END IF ;
	END IF ;
	
	IF IN_TIPOCON <> '' THEN
		IF IN_TIPOCON = 'REG' THEN
			IF IN_IDCONT <> '' THEN
				SET V_WHERE_TBL = V_WHERE_TBL || ' AND TBL.IDCONT = ''' || IN_IDCONT || '''' ;
			ELSE
				SET V_WHERE_TBL = V_WHERE_TBL || ' AND TBL.IDCONT <> ''''' ;
			END IF ;
			IF IN_HEADER <> '' THEN
				SET V_WHERE_TBL = V_WHERE_TBL || ' AND TBL.HEADER = ''' || IN_HEADER || '''' ;
			END IF ;
		END IF ;
		
		IF IN_TIPOCON = 'DEB' THEN
			IF IN_IDCONT <> '' THEN
				SET V_WHERE_TBL = V_WHERE_TBL || ' AND TBL.IDCDEB = ''' || IN_IDCONT || '''' ;
			ELSE
				SET V_WHERE_TBL = V_WHERE_TBL || ' AND TBL.IDCDEB <> ''''' ;
			END IF ;
			IF IN_HEADER <> '' THEN
				SET V_WHERE_TBL = V_WHERE_TBL || ' AND TBL.HEADER2 = ''' || IN_HEADER || '''' ;
			END IF ;
		END IF ;
		
	END IF ;
	
	IF IN_STVAL <> '' THEN
		SET V_WHERE_TBL = V_WHERE_TBL || ' AND TBL.STVAL = ''' || IN_STVAL || '''' ;
	END IF ;
	
	
	SET V_SQL = REPLACE ( V_SQL , '{WHERE}' , V_WHERE ) ;
	SET V_SQL = REPLACE ( V_SQL , '{WHERE_TF}' , V_WHERE_TF ) ;
	SET V_SQL = REPLACE ( V_SQL , '{WHERE_TBL}' , V_WHERE_TBL ) ;
	
	
	/*
	 * Paginado
	 */
	
	IF IO_TOTROW = - 1 THEN
		SET SQLCNT01 = ' SELECT COUNT (*) AS F_TOTROW FROM ( ' || V_SQL ;
	
		SET SQLCNT01 = SQLCNT01 CONCAT ' ) AS TBCOUNT' ;
		
		PREPARE STMTCNT01 FROM SQLCNT01 ;
		OPEN CURCNT01 ;
		FETCH_LOOP :
			LOOP
			FETCH CURCNT01 INTO IO_TOTROW ;
			LEAVE FETCH_LOOP ;
			END LOOP FETCH_LOOP ;
			CLOSE CURCNT01 ;
	END IF ;
	
	SET IO_PAGNUM = PRAXIS . F0001 ( 'PAGNUM' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_PAGROW = PRAXIS . F0001 ( 'PAGROW' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_TOTPAG = PRAXIS . F0001 ( 'TOTPAG' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET IO_TOTROW = PRAXIS . F0001 ( 'TOTROW' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	SET PAGROWINIT = PRAXIS . F0001 ( 'PRINIT' , IO_PAGNUM , IO_PAGROW , IO_TOTPAG , IO_TOTROW ) ;
	
	SET SQLPAG01 = 'SELECT * FROM ( ' CONCAT V_SQL CONCAT ' ) AS       
	RS WHERE RS.RN >  ' CONCAT PAGROWINIT ;
	IF IO_PAGROW > 0 THEN
		SET SQLPAG01 = SQLPAG01 CONCAT ' FETCH FIRST ' CONCAT IO_PAGROW CONCAT ' ROWS ONLY' ;
	END IF ;
	
	
	PREPARE STMTQRY01 FROM SQLPAG01 ;
	OPEN CURQRY01 ;
END;

