
SELECT * FROM PRAXISMP.MPF101
--SELECT bandoc,dateci,tranci, a.* FROM praxismp.mpf102 a
--MPF102 DEPOSITOS => BANDOC DATECI TRANCI
--MPF060 LIQUIDACIONES TOTAL =>BANDOC DATECI TRANCI
--MPF091 GASTOS

--MPF101 LIQUIDACIONES CONCILIADAS
--MPF100 VENTAS/FACTURAS 

-- FILTRAR MPF101 POR IDCONT : SCARNDN,SAUTHOC,SVFOP,SDATE,SCURRENCY,MONEDAPAGO,IMPORTEPAG,SAGENT,MERCHNC, SUBCONSULTA( MPF100 :DATEC, TRANC, CODPRO )


----------------------------------------------------------------------------------


SELECT TBL.*,(TBL.SVFOP - TBL.SUMA_VTA) SUM_DIFF FROM (
SELECT BANDOC,SCARDN,SAUTHOC,SDATE,SVFOP,SCURRENCY,IMPORTEPAG,MONEDAPAGO,SAGENT,MERCHNC,STVAL,GENCON,
(SELECT SUM(CASE WHEN B.TDOC = 'S' THEN ABS(B.SVFOP) ELSE ABS(B.SVFOP) * -1 END) FROM PRAXISMP.MPF100 B WHERE B.DATEC = A.DATEC AND B.TRANC = A.TRANC AND B.CODPRO = A.CODPRO) SUMA_VTA,
(SELECT MAX(SCURRENCY) FROM PRAXISMP.MPF100 B WHERE B.DATEC = A.DATEC AND B.TRANC = A.TRANC AND B.CODPRO = A.CODPRO) MDA_VTA,
(SELECT COUNT(0) FROM PRAXISMP.MPF100 B WHERE B.DATEC = A.DATEC AND B.TRANC = A.TRANC AND B.CODPRO = A.CODPRO) QTY_TKT
FROM PRAXISMP.MPF101 A
WHERE IDCONT='202REGCM12509250916191311'
--AND BANDOC IN ('CM00001514') 
AND TDOC='S' 
AND TDOCORG='' 
--AND STVAL = '1'
AND STVAL IN ('1','5')
) AS TBL 
--WHERE (TBL.SVFOP - TBL.SUMA_VTA) <> 0
ORDER BY SUM_DIFF DESC, GENCON




---SUMADO LOS DOS DEBEN RESTARSE CON EL CAMPO NETO DE LA 60 (CREDOMATIC)
SELECT TDOC,SUM(SVFOP),SUM(TOTAL),SUM(COMISION),SUM(NETO) FROM PRAXISMP.MPF060 WHERE BANDOC = 'CM00001514'
GROUP BY TDOC

SELECT CODIGO,SUM(IMPORTE) FROM PRAXISMP.MPF091 WHERE BANDOC = 'CM00001514'
GROUP BY CODIGO
----------------------------------------------------------------------------------


CALL PRAXISMP.MPS295('202REGCM12509250916085641')





SELECT BANDOC,DATEC,TRANC,SUM(SVFOP)SFVOP,LISTAGG(CCIA||FORMA||SERIE,'-')TKT FROM PRAXISMP.MPF100
WHERE IDCONT='202REGCM12509250916191311'
GROUP BY BANDOC,DATEC,TRANC
ORDER BY BANDOC,DATEC,TRANC
ddffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd

SELECT * FROM PRAXISMP.MPF100 WHERE  IDCONT='202REGCM12509250916191311'



----



---

SELECT SCARDN,SAUTHOC,SVFOP,SDATE,SCURRENCY,MONEDAPAGO,IMPORTEPAG,SAGENT,MERCHNC  FROM PRAXISMP.MPF101



SELECT 
  	A.IDCONT,A.SCARDN, A.SAUTHOC, A.SVFOP, A.SDATE, A.SCURRENCY, A.MONEDAPAGO, A.IMPORTEPAG, A.SAGENT, A.MERCHNC,
    B.DATEC, B.TRANC,B.CODPRO
FROM PRAXISMP.MPF101 A
INNER JOIN PRAXISMP.MPF100 B
       ON A.IDCONT = B.IDCONT
--WHERE A.IDCONT = '202REGCM12509250916191311';
       
       
       
       
       SELECT A.BANDOC,
       A.DATEC,
       A.TRANC,
       A.SFVOP,
       B.TKT
FROM (
    SELECT BANDOC,
           DATEC,
           TRANC,
           SUM(SVFOP) AS SFVOP
    FROM PRAXISMP.MPF101
    WHERE IDCONT = '202REGCM12509250916191311'
      AND TDOC = 'S'
      AND STVAL = '1'
    GROUP BY BANDOC, DATEC, TRANC
) A
INNER JOIN (
    SELECT BANDOC,
           DATEC,
           TRANC,
           LISTAGG(CCIA || FORMA || SERIE, '-') AS TKT
    FROM PRAXISMP.MPF100
    WHERE IDCONT = '202REGCM12509250916191311'
    GROUP BY BANDOC, DATEC, TRANC
) B
ON A.BANDOC = B.BANDOC
   AND A.DATEC = B.DATEC
   AND A.TRANC = B.TRANC
ORDER BY A.BANDOC, A.DATEC, A.TRANC;






CALL PRAXISMP.MPS295('202REGWP12509250919132924')







SELECT TBL.*,
--(CASE WHEN SCURRENCY = MDA_VTA THEN TBL.SVFOP ELSE TBL.IMPORTEPAG END) AS AMOUNT,
((CASE WHEN SCURRENCY = MDA_VTA THEN TBL.SVFOP ELSE TBL.IMPORTEPAG END)- TBL.SUMA_VTA) SUM_DIFF,
COALESCE(NULLIF(TRIM(TBL.MDA_VTA),''), NULLIF(TRIM(TBL.SCURRENCY),''), TBL.SCURRENCY) AS CURRENCY_FINAL
FROM (
SELECT BANDOC,SCARDN,SAUTHOC,SDATE,SVFOP,SCURRENCY,IMPORTEPAG,MONEDAPAGO,SAGENT,MERCHNC,STVAL,GENCON,
IFNULL((SELECT SUM(CASE WHEN B.TDOC = 'S' THEN ABS(B.SVFOP) ELSE ABS(B.SVFOP) * -1 END)
FROM PRAXISMP.MPF100 B WHERE B.DATEC = A.DATEC AND B.TRANC = A.TRANC AND B.CODPRO = A.CODPRO),0) SUMA_VTA,
IFNULL((SELECT MAX(SCURRENCY) FROM PRAXISMP.MPF100 B WHERE B.DATEC = A.DATEC AND B.TRANC = A.TRANC AND B.CODPRO = A.CODPRO),'') MDA_VTA,
(SELECT COUNT(0) FROM PRAXISMP.MPF100 B WHERE B.DATEC = A.DATEC AND B.TRANC = A.TRANC AND B.CODPRO = A.CODPRO) QTY_TKT
FROM PRAXISMP.MPF101 A
WHERE IDCONT='202REGCM12509250916085641'
AND TDOC='S'
AND TDOCORG=''
AND STVAL IN ('1','5')
) AS TBL
ORDER BY SUM_DIFF DESC, GENCON;


SELECT * FROM PRAXISMP.MPF100 WHERE IDCONT='202REGCM12509250916085641'
SELECT * FROM PRAXISMP.MPF101 WHERE IDCONT='202REGCM12509250916085641'





-------------------

SELECT BANDOC,DATEC,TRANC,SUM(SVFOP)SFVOP FROM PRAXISMP.MPF101
WHERE BANDOC IN ('CM00000603') AND
TDOC='S' AND STVAL='1'
GROUP BY BANDOC,DATEC,TRANC
ORDER BY BANDOC,DATEC,TRANC

SELECT BANDOC,DATEC,TRANC,SUM(SVFOP)SFVOP,LISTAGG(CCIA||FORMA||SERIE,'-')TKT FROM PRAXISMP.MPF100
WHERE BANDOC IN ('CM00000603')
GROUP BY BANDOC,DATEC,TRANC
ORDER BY BANDOC,DATEC,TRANC